### ISSUE TITLE
Team Foundation Server 2017 not supported

### ISSUE THREAD

**Issue by scattergood** [microsoft/featuretimeline#100]
I just installed Feature Timeline and Epic Roadmap on my locally hosted Team Foundation Server 2017 version 15.105.325910.0

I saw on the Marketplace page that the versions supported are:

Works with
Azure DevOps Services
Team Foundation Server 2017 Update 2
Team Foundation Server 2017 Update 3
Team Foundation Server 2018
Azure DevOps Server 2019

Despite this I get the message of "This extension is supported on Team Foundation Server 2018 or above."

How do I resolve this issue without having to upgrade to TFS 2018?

Thanks.

**Comment by navneet-g** [comment]
This seems like RTM of 2017, can you upgrade to Update 2 of 2017 and try again?

**Comment by joshdavidson613** [comment]
I upgraded to Update 2 (not a fun process) and the Feature Timeline comes up! However the Epic Roadmap (beta) initiates but has the waiting circle gif going forever.

Thanks for the help.

**Comment by navneet-g** [comment]
@joshdavidson613  There might be some errors in Chrome console, please take a look and share.

**Comment by joshdavidson613** [comment]
There were in the following Name / Response pairing:

backlogconfiguration
---------------------
{"message":"TF400813: Resource not available for anonymous access. Client authentication required.","type":"Microsoft.TeamFoundation.Framework.Server.InvalidIdentityException","isRemoteException":false,"errorCode":0,"eventId":3000}

EpicRoadmapeef83f86-543b-4faa-964a-9fa75bfcf137_settings 
--------------------------------
{"$id":"1","innerException":null,"message":"TF1590005: Document with id $settings does not exist in collection User for 1ddbd832-0404-43be-8956-ecc62f0fd4d6 = EpicRoadmapeef83f86-543b-4faa-964a-9fa75bfcf137_settings","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentDoesNotExistException","errorCode":0,"eventId":3000}

EpicRoadmapeef83f86-543b-4faa-964a-9fa75bfcf137_iterationDisplayOptions
-------------------------------
{"$id":"1","innerException":null,"message":"TF1590005: Document with id $settings does not exist in collection User for 1ddbd832-0404-43be-8956-ecc62f0fd4d6 = EpicRoadmapeef83f86-543b-4faa-964a-9fa75bfcf137_iterationDisplayOptions","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentDoesNotExistException","errorCode":0,"eventId":3000}

backlogconfiguration
--------------------------------
{"message":"TF400813: Resource not available for anonymous access. Client authentication required.","type":"Microsoft.TeamFoundation.Framework.Server.InvalidIdentityException","isRemoteException":false,"errorCode":0,"eventId":3000}
