### ISSUE TITLE
Removing a feature

### ISSUE THREAD

**Issue by markrichbaker** [microsoft/featuretimeline#101]
Hi - Once a feature is on the feature roadmap I can't seem to remove it. We have a large feature backlog and only want to schedule a subset of these, also we may want to remove / un-schedule a feature once it's on the roadmap.

I've tried everything including clearing iterations and resetting the iterations for the feature to no avail.

**Comment by imega75** [comment]
Yes, this is really annoying. There needs to be a way to drop features off the timeline.

**Comment by chris-wessels** [comment]
This has been driving me bonkers too but I do seem to have found a way of doing it. Ideally I would just like to drag the feature back onto the _plan features_ bar from where I dragged it onto the timeline in the first place.
However, this seems to work for me...

1. In Timeline view of the feature, set the start and end iterations back to the root path
2. Open the feature and ensure it is not indexed against an iteration. If it is, set it back to the root iteration path.

That should remove it. If not, check if there are any child items of the feature that are indexed to an iteration. If they are, set them back to the root iteration path.

**Comment by apurvashukla** [comment]
I'd vote for this feature too as even though @chris's method gets the feature out of the timeline, but now I've lost information on this future item. There are times when I just want current PI items to show up and not enlarge the canvas because of these future items.

**Comment by pvginkel** [comment]
I couldn't find how to set the start and end iteration of the feature.

If you hover over it, you can an "i" icon:

![image](https://user-images.githubusercontent.com/828966/163954213-a1bee40d-0590-4ae2-9ee3-165769212599.png)

The start and end iteration are at the bottom of the screen the button opens.
