### ISSUE TITLE
Help Wanted: Development of few features

### ISSUE THREAD

**Issue by dlorych** [microsoft/featuretimeline#104]
Hi, in my organization, we're looking into extending this extension with few new features:
- filter-bar, similar to one in Boards view, filtering on status and tags attributes
- start and end iteration filter to narrow timeline (that would change the current View Sprints input)
- a way to distinguish features (work-items) visually on a timeline, e.g. adding work-item icon (here I mean having customized process and new work-item on Feature level, other that default Feature)

1. Do these features are inline with your vision of extension?

2. I am a bit new to Azure DevOps and its SDK, and I will need help from a mentor on how to best tackle such development. Any volunteer?

**Comment by navneet-g** [comment]
These will be great features, I can help you ramp up.
Please send me an email at navneetg@microsoft.com and I can schedule a quick meeting.

**Comment by navneet-g** [comment]
Closing this issue for now, Please let me know when you are available.
