### ISSUE TITLE
Features not showing for future sprints and future sprints not always show

### ISSUE THREAD

**Issue by JThomas77** [microsoft/featuretimeline#105]
Hello,

When first clicking on Feature Timeline we are only shown ## of 34 sprints as ## can vary. We have to change the View Sprints number a few times till all iterations show up, currently that number is 34. However not all the features are showing all the way out to the 34th sprint. 
![FeatureTimelineBug](https://user-images.githubusercontent.com/49654460/56155849-b63df380-5f70-11e9-935b-5f2077860efa.png)

**Browser**
Choose a browser
[x] IE11
[x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by navneet-g** [comment]
Feature timeline shows only In Progress sprints the others can be pulled in if needed using "Plan features"
