### ISSUE TITLE
Add ability to export to PDF

### ISSUE THREAD

**Issue by ynijsen** [microsoft/featuretimeline#106]
For sharing our roadmap with stakeholders we would like to export to a PDF file. 
Printing the current page results in an empty frame. 
This also allows to create a moment in time snapshot of the project.

**Comment by QA1-Skip** [comment]
that would work for us as well

**Comment by ikanda** [comment]
Export to an image should be also handy for us.

**Comment by LouisMQc** [comment]
that would be awesome to present project features planning to top management

**Comment by fhack2** [comment]
I had a couple of teams in our organizations that started using this ask if there was a way to export the Feature Timeline. Looks like they are very interested in having an export option.

**Comment by ynijsen** [comment]
What build is it released in?
