### ISSUE TITLE
Hide past sprints

### ISSUE THREAD

**Issue by Caz1985** [microsoft/featuretimeline#108]
Feature Timeline - Is it possible to hide past prints in the feature timeline view?

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

![Feature Timeline snip](https://user-images.githubusercontent.com/50668333/57782428-21bbe200-7724-11e9-8117-379dd2a74e8f.JPG)

Thanks

**Comment by waynethompson** [comment]
This would be awesome. We have sprints dating back a couple of years.
Should probably make a new board i guess

**Comment by navneet-g** [comment]
@waynethompson  and @Caz1985 Feature timeline uses the Sprints subscribed by the team in the Team configuration section. You can remove the sprints there to exclude them from Teams's view.

**Comment by Caz1985** [comment]
If I remove sprints from the team configuration I can't use the widgets on my dashboard to show what our team have delivered for that sprint. Will there be a hide previous sprints feature introduced?

**Comment by navneet-g** [comment]
Thanks @Caz1985 , I will consider this for next major release. But no promise on ETA :).

**Comment by ikanda** [comment]
Yes, i'd love this as well.

**Comment by dugsdad** [comment]
The option to show a beginning/ending range of iterations would be helpful. The UI almost seems to suggest that one could request sprints "greater than" a given iteration by showing the ">" symbol, but then it's not allowed as a valid entry if you attempt to key it into the text box.

**Comment by schmitzel76** [comment]
Hiding past iterations would surely improve usability for us. If I now want to plan ahead, for, for example 5 sprints, I have to set _View Sprints_ to 10 and then scroll halfway. It would be nice not having to do that.

I would propose having options like:

* Show current sprint and the specified number of sprints after
* Show current sprint and the specified number of sprint before
* Show current sprint and the specified number of sprints before and after or just supply a range of sprints
