### ISSUE TITLE
Feature request - Adding releases

### ISSUE THREAD

**Issue by MajkiMich** [microsoft/featuretimeline#109]
Hi,
love your timeline feature!
We are looking for the possibility to add releases (or other milestones) on the timeline - as a pin or maybe a line - to indicate the close of development cycle.

If there is such a feature - how can it be found? if not, is this something you might be willing to implement? 

Thank you!
Mike

**Comment by navneet-g** [comment]
Thanks @MajkiMich for kind words. This is a great suggestion. I will keep it in mind for next major release. Currently I am bit busy with my work so I do not have an ETA.
If you know a developer who can help, that would be awesome.

**Comment by MajkiMich** [comment]
Awesome, thanks @navneet-g 
I will ask around, maybe one of my friends will have some time :)
PFA mock-up of what we were thinking about. 
Inlcuding coloring of feature cards on the timeline - it is do-able on the board for other items, it should be possible to add to your feature as well

Mike

![Mock](https://user-images.githubusercontent.com/51411390/58968149-d42c1580-87b5-11e9-99d4-2b8b5cbf076e.png)

**Comment by MajkiMich** [comment]
Hi @navneet-g, any news on those features?
