### ISSUE TITLE
Start of Feature Bars in Release Not Corresponding to Story Start Dates

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/featuretimeline#11]
First off, GREAT WORK!!

Can you please explain the logic that determines where the start of the feature bars are placed? I assumed it was to be the start of a user story being transitioned from proposed to the active state, but that does not seem to line up with our situation.

TIA!
MR
PS. Do you have a place for submitting feedback and suggestions for new capabilites?

**Comment by navneetg-msft** [comment]
@maxxis, can you give me an example? Please ensure that the team subscribes to the iterations the stories are in.

Please feel free to create issues for feature requests.

**Comment by maxxxis** [comment]
Here is an example of what I'm asking for:

**Comment by maxxxis** [comment]
![image](https://user-images.githubusercontent.com/28545851/41628372-1472e80e-73d9-11e8-9ae2-fb2c8c2149c5.png)

**Comment by navneetg-msft** [comment]
Thanks @maxxis ... is the team still subscribes to those sprints that finished long ago? If not then we do not consider those sprints. 
![image](https://user-images.githubusercontent.com/27786230/41660363-b4f1bebe-7450-11e8-931a-1c72eff94c71.png)

**Comment by maxxxis** [comment]
@navneetg-msft, can you please explain what you mean by subscribed? Also, what do you mean by long ago, is that supposed to mean greater than 5 sprints?

**Comment by navneetg-msft** [comment]
@maxxxis I can setup a quick skype call and we can go over this, it will be easier to communicate.
Please send me an email at navneetg@microsoft.com and I can setup a call.

**Comment by navneetg-msft** [comment]
As we have not heard back on this for about 3 weeks, we are closing the issue. Please reopen when you have time to work on it.
