### ISSUE TITLE
I have installed the extension but the tabs are not showing

### ISSUE THREAD

**Issue by Hlovbeyond** [microsoft/featuretimeline#110]
Running on Prem 
Microsoft Visual Studio Team Foundation Server
Version 15.117.26714.0

**Comment by navneet-g** [comment]
Please share a screenshot of where you were expecting tabs to be shown.

**Comment by bchayer** [comment]
HI Folks,

I am experiencing the same problem on TFS 16.131.2770.1 (TFS 2018 Update 2)

**Comment by navneet-g** [comment]
Thanks @Hlovbeyond  and @bchayer  ... as asked earlier please share the screenshot of where you are expecting the tab to be shown.

**Comment by bchayer** [comment]
I expect to see it on the right of the "Capacité" (Capacity) tab 

![image](https://user-images.githubusercontent.com/52242722/60201780-1ece0a00-9817-11e9-9668-da75675aae87.png)
