### ISSUE TITLE
Can not view progress in feature

### ISSUE THREAD

**Issue by kobyb1988** [microsoft/featuretimeline#119]
**Describe the bug**
I Set story points in my stories in to the feature and in Feature Timeline I can see for example 0/64. This is the progress at start time. After that I do not undestand how I can change the progress state. I've tried change remaining in tasks, completed in task and UserStory, but nothing any cnanged in my view in Feature Timeline. 

**Browser**
Choose a browser

[ ] Chrome
**Version**
[ ] Azure DevOps/VSTS
**Screenshots**
![Error 1](https://user-images.githubusercontent.com/6911180/60166222-0f43c680-9801-11e9-937a-8101a3c27c24.PNG)
![Error 2](https://user-images.githubusercontent.com/6911180/60166357-53cf6200-9801-11e9-80bd-2e74848d3d35.PNG)
![Error 3](https://user-images.githubusercontent.com/6911180/60166367-58941600-9801-11e9-8007-7589d25c271f.PNG)

**Comment by navneet-g** [comment]
Thanks @kobyb1988 the screen shotfor 6701 are the efforts for tasks, not story points. The story points are the one described in 6647. The story 6647 is still active, once it is completed/closed then the Feature timeline will show the progress.
