### ISSUE TITLE
Story with defined sprint are displayed in the timeline details backlog column.

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/featuretimeline#12]
**Describe the bug**
Subset of stories with a defined sprint are displayed in the timeline details backlog column.

**Browser**
Choose a browser
[ ] IE11
[ x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] VSTS
[ ] TFS 2017 Update 2/3
[x ] TFS 2018.2

**Screenshots**
![image](https://user-images.githubusercontent.com/28545851/41493311-caf36d3c-70ba-11e8-8913-cb9366a77f0e.png)

![image](https://user-images.githubusercontent.com/28545851/41493329-f9e40750-70ba-11e8-89f2-303d325539bc.png)

**Comment by navneetg-msft** [comment]
@maxxis, can you check if the team subscribes to this iteration?

**Comment by maxxxis** [comment]
@navneetg-msft, I'm not sure what you're asking about. Are you asking if they subscribe to notifications, in which case, I'm confused. However, if you are you asking if they are assigned to stories within the sprint, then the answer is yes. They are assigned via the Capacity tab. All stories have someone assigned to the stories in the sprint backlog.

**Comment by navneetg-msft** [comment]
@maxxis Please take a look at this https://docs.microsoft.com/en-us/vsts/work/scale/set-team-defaults?view=vsts#select-team-sprints-and-default-iteration-path

**Comment by Maxxis** [comment]
@navneetg-msft, please stop mentioning me in several issues, im not interested in your work.

**Comment by maxxxis** [comment]
@navneetg-msft, what specifically are you wanting me to refer to on that page? I have my default Sprint and have a few past present and future Sprint active, but I'm not sure what you're asking for me to do. That's said, does your feature timeline use those active Sprint's as what is referenced for the start and end of your bars in some way? Also please note my username has an extra X.

**Comment by navneetg-msft** [comment]
As we have not heard back on this for about 3 weeks, we are closing the issue. Please reopen when you have time to work on it.
