### ISSUE TITLE
Is there any way to disable the "Portfolio Plans (beta)" tab?

### ISSUE THREAD

**Issue by kjuhas** [microsoft/featuretimeline#128]
**Describe the bug**
Is there any way to disable the "Portfolio Plans" tab? 

Our organization loves this plugin, but we recently rcvd an update that added the "Portfolio Plans (beta)"  tab without any notification. We have a governance process and are using this extentions in a very specific way with our IT SDLC. We would like to disable the new tab but still use the existing feature within the Boards & Backlog tabs.  

**Browser**
Choose a browser
[ ] IE11
[X ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
![2019-07-18_9-09-52](https://user-images.githubusercontent.com/53047822/61460018-ee701c00-a93b-11e9-9517-1627d652f973.jpg)

[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by navneet-g** [comment]
Thanks @kjuhas unfortunately currently there is no way to disable Portfolio Plans Hub.
