### ISSUE TITLE
Feature Request: Provide ability to filter Epics on Feature timeline

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/featuretimeline#13]
As a user, I want to be able to filter out the epics that I don't want to see on the timeline, so that I can simplify what is displayed.

**Comment by navneetg-msft** [comment]
Thanks @maxxxis this is already planned for a future release.

**Comment by navneetg-msft** [comment]
We just released a new Feature in Beta called Epic Roadmap where you can see expanded details about individual Epic including what all teams/Area paths working on the features and their dependencies. Please give it a try and let us know if  you have any feedback.
