### ISSUE TITLE
Use Feature Timeline in a Dashboard

### ISSUE THREAD

**Issue by jh0274** [microsoft/featuretimeline#134]
Hi 

Our business users have access to dashboards that allow them to track their requests.  I would like to add the feature timeline into that dashboard so that they can see a timeline of when features are likely to be ready.  

I've tried using Iframe (pointing to the URL of the feature timeline in the backlog) but that doesn't work (let me know if this is supported)..  

Making the timeline available via iframe (ie the 'Embedded Webpage' widget on the dashboard) or as a separate widget, would both be acceptable to me.

Thanks!

**Comment by navneet-g** [comment]
Thanks @jh0274 for the feedback, currently the extension does not support this feature. The code is open sourced and we are open for contributions if you can help adding this feature.

**Comment by jh0274** [comment]
Thanks!  I'm wondering why it doesn't work with iframe out of the box. The html seems to allow it...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by navneet-g** [comment]
The extension uses context from the Backlog/Board it is displayed in that context is not available in an iframe somewhere else.

**Comment by jh0274** [comment]
thank you for your quick feedback!
