### ISSUE TITLE
Feature Request: can display parent initiative that has different area path

### ISSUE THREAD

**Issue by gclclg** [microsoft/featuretimeline#143]
###New Feature request: able to display the parent initiative in feature timeline which is not in the same area path with the requirement. This is required when try to use feature timeline to create roadmap for a  program level product that contains multiple projects/teams. ### 
![Capture](https://user-images.githubusercontent.com/53278107/61827564-78cbea80-ae2a-11e9-94b7-948a8f7b30b1.JPG)

**Comment by grubster8** [comment]
Hi, we are looking for a similar feature.  We have an Epic on Project 1, but features that are linked to that Epic do not show up on the Feature Timeline or Epic Roadmap.  Please let us know if this can be done.
