### ISSUE TITLE
Team Foundation Server 2017 Community not supported

### ISSUE THREAD

**Issue by VincentNolan** [microsoft/featuretimeline#145]
Hello, this is a kind of related issue with #100 ,but couldn't see the answer.

I use TFS 2017 community edition and wanted to install this extension. But it gave "This extension is not installable on any currently installed products." exception.
Then I upgraded to TFS 2017 community update 2 and still have the same exception.

No support for community editions ?

**Comment by nschonni** [comment]
Community is a Visual Studio edition, not a TFS edition. Are you trying to install the VSIX by double clicking on it?

**Comment by VincentNolan** [comment]
I have TFS Express, and yes trying to install by double clicking.

**Comment by nschonni** [comment]
You can't double click install VSIX for TFS extensions. There are instructions on the docs site if you search
