### ISSUE TITLE
Remove Portfolio Plans notification on-prem

### ISSUE THREAD

**Issue by pascalberger** [microsoft/featuretimeline#146]
**Describe the bug**
While opening Feature Timeline or Epic Roadmap in Azure DevOps Server 2019 I still get a notification which asks me to try Portfolio Plans which are now disabled.
Clicking on it will end on a 404 page since this feature is no longer available on-prem. The notification should also be removed therefore.

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[x] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018
[x] Azure DevOps Server 2019

**Screenshots**

![grafik](https://user-images.githubusercontent.com/2190718/62062259-f3c94280-b228-11e9-88ac-c3acce1d48e9.png)

**Comment by fmuecke** [comment]
Same here.

**Comment by shutchings** [comment]
Thanks for the feedback! This is fixed in the new release.
