### ISSUE TITLE
Feature Request: Display leading/trailing arrow when feature band starts/ends beyond the displayed sprints

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/featuretimeline#15]
As a user, I want to be able to visually differentiate when feature bars start/end beyond the displayed sprints from those that start end on the sprints when the bar's end is the rounded square.
![image](https://user-images.githubusercontent.com/28545851/41629305-99d40a42-73dd-11e8-9dac-da57dda817e7.png)

**Comment by navneetg-msft** [comment]
@maxxis what version do you have it installed? We already show following when you are in 3 or 5 sprint view
![image](https://user-images.githubusercontent.com/27786230/41660164-2698a25e-7450-11e8-8b2c-e44d25f02d3f.png)

**Comment by navneetg-msft** [comment]
Closing due to no response.
