### ISSUE TITLE
work items with a status of Removed are displayed when adding items to the project plan

### ISSUE THREAD

**Issue by brandonmcclure** [microsoft/featuretimeline#155]
I create a plan, and click the Add Items button, and select the project. I then get a list of work items (it says they are Epics, but we do not use that work item type, so it is only features.) This list includes features that have a status of _removed_, making it difficult for us to find the features that we want to plan for.

I think the way I would want this to work is that I have the ability to set a filter to only include work items with a state of X when I add items. That would give me the freedom to use custom states as needed while still letting me find the features that I want to plan out quickly.

**Browser**
Choose a browser
[ ] IE11
[ x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by ezambra** [comment]
Hi @brandonmcclure .
Thanks for reporting the issue.
We just released an update that includes a filter in the `Add Items` panel. Filter works on the work item title and id as well. 
We also added a context menu action to the work item, so you can now add work items directly from your Backlog / Board.
