### ISSUE TITLE
User not able to view Plan

### ISSUE THREAD

**Issue by shefali-bedi** [microsoft/featuretimeline#162]
**Describe the bug**
I have a user that has all necessary permissions- project admin and Allow 'View/Edit Analytics Permissions' in Azure DevOps project. He holds Stakeholder license and gets an error while trying to view a Plan i created. If i give him 'Basic' license he is able to view the Plan.
Can you please help me

**Browser**
Choose a browser
[ ] Chrome

**Version**
[ ] Azure DevOps/VSTS

**Screenshots**
Access to data from Analytics OData endpoint is not available for all users.

**Comment by jaredfholgate** [comment]
One of my colleagues has the same issue. The full error message is;

"VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account."

They have a 'Basic' license assigned. I created the plan using my Visual Studio Enterprise licensed account. 

This is in Azure DevOps Service with version 17.158.0.1266795967 of the Delivery Plans extension.
