### ISSUE TITLE
Dependencies are really missing from the feature

### ISSUE THREAD

**Issue by shmulikah** [Microsoft/featuretimeline#17]
Great work guys but one thing that is really missing in VSTS/TFS is visualization of Dependencies between work items.
even the simplest Dependencies such as predecessor and successor are not getting any visual representation.
any plans on delivering dependency management and visualization in Feature timeline (or even Delivery plans)?

**Comment by navneetg-msft** [comment]
Thanks for the feedback @shmulikah ...we are thinking about features for the next version ... I will keep this feedback in mind.

**Comment by davesmits** [comment]
I would love to have this as well! +1

**Comment by navneetg-msft** [comment]
You asked ... we listened :) ... we have released a new Tab in Beta called Epic Roadmap where you can see predecessors and successors, please try it out and give us some feedback.

**Comment by awsrijckaert** [comment]
Would also like to see the dependencies in the Portfolio Plans between the work items (Epics). When will that be available?
