### ISSUE TITLE
Epic roadmap "team not subscribed" to teams backlog iteration

### ISSUE THREAD

**Issue by JGCreator** [microsoft/featuretimeline#170]
**Describe the bug**
The Epic Rollup is saying that my team is not subscribed to the iteration set to the teams backlog iteration, and nothing is shown.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

![image](https://user-images.githubusercontent.com/5280734/62794875-de5ede80-ba9a-11e9-9dce-4de92127e1ce.png)
![image](https://user-images.githubusercontent.com/5280734/62794883-e585ec80-ba9a-11e9-957b-1ccc102fbb1b.png)

**Comment by navneet-g** [comment]
Thanks Josh ... the SYB\Backlog is in Backlog iteration but not one of the iterations in the selected iteration. It has to be one of the selected iterations in the list.

**Comment by JGCreator** [comment]
How can I add the `SYB\Backlog` iteration to the iteration(s) list without destroying the list of others?
![image](https://user-images.githubusercontent.com/5280734/62800065-0a349100-baa8-11e9-8274-7cdadaaf78f5.png)

It seems that the only way to get a view on any of these Epics is to move the epic into a sprint, which seems very counter intuitive since the definition of Epic is larger than any individual iteration.

**Comment by navneet-g** [comment]
Yes ... unfortunately this is one of the design choices made in the product itself.

**Comment by JGCreator** [comment]
Okay. I'm still having an issue with seeing anything when I have an Epic in an iteration with features in sub iterations (sprints) and stories for those features in their respective sprints.

Team iteration list:
![image](https://user-images.githubusercontent.com/5280734/62800951-4963e180-baaa-11e9-99e5-a479b3ae0cc7.png)
