### ISSUE TITLE
Not running in TFS

### ISSUE THREAD

**Issue by Godardd** [Microsoft/featuretimeline#18]
Hi, we are trying to get your add-in to run on our TFS env but we are getting a SCRIPT5: Access is denied. error in IE, Firefox and Chrome any suggestions would be greatly appreciated. Please note that we have successfully used other Market Place add-ins in this environment.

**Comment by Godardd** [comment]
15.117.26615.0, yes here they are: 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/594afd2f-f489-4975-ab48-4255b213bd2e_iterationDisplayOptions:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/Default/Current/Collections/%24settings/Documents/overriddenWorkItemIterations:1 Failed to load resource: the server responded with a status of 404 (Not Found)
VM22 Content:5 GET /tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/594afd2f-f489-4975-ab48-4255b213bd2e_settings 404 (Not Found)
send @ VM22 Content:5
ajax @ VM22 Content:5
(anonymous) @ VM26 Content:52
c @ VM26 Content:28
(anonymous) @ VM26 Content:28
u.promiseDispatch @ VM26 Content:28
(anonymous) @ VM26 Content:28
t @ VM26 Content:28
VM120 react-dom.js:62 TypeError: Cannot read property 'length' of null
    at u (VM118 bundle.js:1)
    at VM118 bundle.js:1
    at Array.map (<anonymous>)
    at c (VM118 bundle.js:1)
    at u (VM118 bundle.js:1)
    at VM118 bundle.js:1
    at Array.map (<anonymous>)
    at c (VM118 bundle.js:1)
    at l (VM118 bundle.js:1)
    at t.getEpicHierarchy (VM118 bundle.js:1)
```

**Comment by navneetg-msft** [comment]
We just released an update ... can you try again?

**Comment by navneetg-msft** [comment]
Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by Godardd** [comment]
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by navneetg-msft** [comment]
Sure ... What time suits you today?


On Aug 2, 2018 03:26, Daniel Godard <notifications@github.com> wrote:
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by Godardd** [comment]
Sorry, my day got overrun by events, would you be available tomorrow morning around 10?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 9:06 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


Sure ... What time suits you today?


On Aug 2, 2018 03:26, Daniel Godard <notifications@github.com> wrote:
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by navneetg-msft** [comment]
10 am PST tomorrow morning is fine with me.

On Aug 2, 2018 12:19, Daniel Godard <notifications@github.com> wrote:
Sorry, my day got overrun by events, would you be available tomorrow morning around 10?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 9:06 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


Sure ... What time suits you today?


On Aug 2, 2018 03:26, Daniel Godard <notifications@github.com> wrote:
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by Godardd** [comment]
Ok will send you and invite, cheers !

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 3:50 PM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


10 am PST tomorrow morning is fine with me.

On Aug 2, 2018 12:19, Daniel Godard <notifications@github.com> wrote:
Sorry, my day got overrun by events, would you be available tomorrow morning around 10?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 9:06 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


Sure ... What time suits you today?


On Aug 2, 2018 03:26, Daniel Godard <notifications@github.com> wrote:
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by Godardd** [comment]
Good morning, what email address should I use to send you the invite ?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 3:50 PM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


10 am PST tomorrow morning is fine with me.

On Aug 2, 2018 12:19, Daniel Godard <notifications@github.com> wrote:
Sorry, my day got overrun by events, would you be available tomorrow morning around 10?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Thursday, August 2, 2018 9:06 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)


Sure ... What time suits you today?


On Aug 2, 2018 03:26, Daniel Godard <notifications@github.com> wrote:
Good morning Navneet, unfortunately we have having the same issue with the latest version, we get many 404 against the package. would you be available for a WebEx to look at what is going on?

Sent from my BlackBerry 10 smartphone on the Bell network.
From: NAVNEET GUPTA
Sent: Tuesday, July 31, 2018 2:28 AM
To: Microsoft/featuretimeline
Reply To: Microsoft/featuretimeline
Cc: Daniel Godard; Author
Subject: Re: [Microsoft/featuretimeline] Not running in TFS (#18)



Closing as we did not hear back, please reopen if are still facing this issue.

**Comment by navneetg-msft** [comment]
navneetg@microsoft.com

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by navneetg-msft** [comment]
I have not received the invite yet, are we meeting at 10:30?
________________________________
From: Navneet Gupta <navneetg@outlook.com>
Sent: Friday, August 3, 2018 7:20 AM
To: Microsoft/featuretimeline; Microsoft/featuretimeline
Cc: State change
Subject: RE: [Microsoft/featuretimeline] Not running in TFS (#18)


navneetg@microsoft.com



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________
