### ISSUE TITLE
Portfolio Plans: Unable to Delete Work Item from Plan

### ISSUE THREAD

**Issue by judychou** [microsoft/featuretimeline#181]
After adding work items (ex: epic) to a Portfolio Plan, we are not able to delete the work item from the plan.  This feature is needed.  Otherwise, the only option is to recreate the entire plan, which may deter stakeholders from using this.

**Comment by shutchings** [comment]
@judychou have you used the ... button at the top of the plan? You should be able to remove the selected work item from the plan. 

![image](https://user-images.githubusercontent.com/30058280/63035618-513bd100-be70-11e9-9d9a-7f59b5200968.png)

In a future release we will be moving this to a context menu on the plan item.

**Comment by judychou** [comment]
Thanks for clarifying.  I am able to remove the selected work item from the plan now.

Judy Chou
Senior Quality Assurance Engineer, Enterprise Technology

Direct     206-393-5888
Other     206-674-3400
Email      judy.chou@expeditors.com

[cid:image001.gif@01D5527D.A13A2670]

Global Headquarters, Seattle
1015 Third Avenue, 2nd Floor
Seattle, WA 98104
