### ISSUE TITLE
Portfolio Plans: Hard to Find Epic to Add to Plan

### ISSUE THREAD

**Issue by judychou** [microsoft/featuretimeline#182]
We find it difficult to find the Epic to add to the Portfolio Plan because the list is too long.  It includes Epics in all states from every team within a project.  We have close to 1500 Epics in our project and the list does not seem to be sorted in any way! We would like to see a textbox allowing us to search by ID.  This will save us a lot of time.

**Comment by shutchings** [comment]
@judychou thanks for the feedback! This is something we're looking at implementing in the future.

**Comment by judychou** [comment]
Any estimates on when?

Judy Chou
Senior Quality Assurance Engineer, Enterprise Technology

Direct     206-393-5888
Other     206-674-3400
Email      judy.chou@expeditors.com

[cid:image001.gif@01D5527D.AFAE4100]

Global Headquarters, Seattle
1015 Third Avenue, 2nd Floor
Seattle, WA 98104

**Comment by shutchings** [comment]
It's being worked on now and will be part of the next release. Probably in the next couple weeks.

**Comment by ezambra** [comment]
Hi @judychou 
Thanks for reporting the issue.
We've added a filter that works on the work item title / id.
There is now also a context menu option in the work item to add work items directly from your Backlogs / Boards.
