### ISSUE TITLE
Support direct link to selected epic in Epic Roadmap

### ISSUE THREAD

**Issue by pascalberger** [microsoft/featuretimeline#199]
I couldn't find a way to have the epic selection pre-defined through a link. It would be nice to have the possibility to pass the epic which should be selected in the Epic Roadmap through a link, so that it can be shared.

**Comment by mzdimal** [comment]
I am not sure if this is the same thing you are requesting, but I would simply like to be be able to click the Epic title and open the Epic details. As a bar minimum, add the option to the ellipse.
