### ISSUE TITLE
Align the card styling more with VSTS

### ISSUE THREAD

**Issue by davesmits** [Microsoft/featuretimeline#20]
Curernt the card style is totally different then VSTS. Although I see some difference as alignment of text is needed give extra clearance a more consistent look and feel would be great. I suggest to bring the styling bit more to VSTS. 

Beside that more information in the cards would be useful; especially: 
- ID
- Assigned
- Tags

**Comment by navneetg-msft** [comment]
Thanks @davesmits for feedback. We will consider it in next major release.
