### ISSUE TITLE
Feature request: Portfolio Plans start and end time should auto pick from work items's iteration path. Or from all children's iteration time. 

### ISSUE THREAD

**Issue by gclclg** [Microsoft/featuretimeline#204]
**Describe the bug**

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by xkmarcink** [comment]
It's essential feature to help up manage big backlogs. Any feedback on planned release date? ;)
