### ISSUE TITLE
Progress Tracker not showing and sort order

### ISSUE THREAD

**Issue by krisloe** [microsoft/featuretimeline#205]
I've added several epics to a portfolio and a couple of them don't show progress either with effort or completed count.  I've compared the ones that work to those that don't (area path, status, etc) but don't see a difference as to why some do show progress and the others don't.

Also, what determines the sort order for a project's epics that are added?  I can't figure that out either.  I've tried removing them and adding them in the order I want to see them but they get sorted the same way regardless.

**Comment by ezambra** [comment]
Hi @krisloe 

**re: "Transfer Center Escalation" epic**: we've run into the same problem before on our side. Some work items are not sync'ed with the [OData service](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/?view=azure-devops) - which we use to retrieve roll-up values-. Updating the work item -e.g. changing its state to `Active` - triggers a data transform that starts syncing data. I'll let the Analytics team know about this issue, thanks for reporting it.

**re: 4.14 not showing progress**: We only count user stories, which is the default work item type for requirement backlog levels. @danhellem -our PM- FYI about a feature request to also include `Bugs` in the roll-up values.

Thanks,
__Eduard.
