### ISSUE TITLE
Any user can delete Portfolio Plans

### ISSUE THREAD

**Issue by Xizindar** [Microsoft/featuretimeline#206]
Describe the bug
I have a user who can delete my plans and add their epics to my portfolio plan, even when they are not associated with the plan or project.  We have too many teams to allow for any user to modify plans of portfolios they are not associated with.

Browser
Choose a browser
[ X ] Chrome

Version
[ X ] Azure DevOps/VSTS

Screenshots
No screen shot, but to replicate do the following:
1. Create a portfolio plan from Project X and add any epic.
2. Have a separate user not associated with Project X, log into Project Y and view the portfolio plans.
3. Add an epic from Project Y into new portfolio plan alongside Project X's epic.  (success even though they will not see the Epic from Project X).
4. Delete Portfolio Plan (Plan with epics from Project X and Project Y will be deleted).

**Comment by danhellem** [comment]
Thanks for the suggestion. We are thinking about only those people who created the plan can delete it. Would that work for you?

**Comment by NotaHotmesstoday** [comment]
That would make alot more sense, also people who don't have permission to view a project instance shouldn't be able to modify a plan.

We tested that and I could add to a plan that I didn't have access to see.

**Comment by Xizindar** [comment]
Apologies for the late reply, but yes that would work Dan.

**Comment by NotaHotmesstoday** [comment]
any updates on this?

**Comment by itpropro** [comment]
When will this be fixed? I cannot tell any customer that all people can create, modify AND delete their Portfolio plans...

**Comment by danhellem** [comment]
It's open source so feel free to create a PR. Right now our investment has stalled but we are looking to pick things back up in summer
