### ISSUE TITLE
Missing feature from planning list

### ISSUE THREAD

**Issue by GreenDavidA** [Microsoft/featuretimeline#21]
**Describe the bug**
I have an epic with several features associated with it. All but one feature is displaying in the plan features pane. I've confirmed the feature is properly associated with the parent, in the backlog iteration, is not closed, has its own children configured correctly. All other features seem to be displaying.

**Browser**
Choose a browser
[ ] IE11
[x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ x] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/34946195/42891766-234a4b86-8a7e-11e8-988e-c582d4a9e5ee.png)
![image](https://user-images.githubusercontent.com/34946195/42891779-2d751384-8a7e-11e8-9d12-b3fc566d8fa6.png)

**Comment by navneetg-msft** [comment]
Thanks @GreenDavidA  for reporting the issue. Is the feature in same Area Path and Project as other features?
Also how many total features you see in the Planning Pane, I believe we show only first 200 unplanned items in the planning pane.

**Comment by GreenDavidA** [comment]
They are all in the same project and area path. It may be close to 200 features. What is the sort order? This feature was newer than others, but I moved towards of the top of the backlog.

**Comment by navneetg-msft** [comment]
Can we setup a quick Skype meeting to go over the details and do some live debugging? Please send an email to navneetg@microsoft.com if you are available.

**Comment by Arjy** [comment]
Was this ever resolved. I am having exactly the same problem. Thanks

**Comment by navneetg-msft** [comment]
I am still looking for a repro ... will you have time for a skype call?

**Comment by Arjy** [comment]
Yea sure – can you do it now?

Best regards,
Dr Arji Bhogal

Engineering Manager
[w2logo]
Clarence House, Clarence Place, Newport, NP19 7AA
Tel:+44 (0)330 088 9542
Skype For Business: Arji.Bhogal@w2globaldata.com
Web: www.w2globaldata.com<http://www.w2globaldata.com/>
Technical Support: support@w2globaldata.com<mailto:support@w2globaldata.com>

Subscribe to our newsletter<https://w2globaldata.us12.list-manage.com/subscribe?u=4d6f5011ee8abd9b9c4da1f63&id=9d4b1c48de>

[cid:image002.gif@01D42AFF.367D5EC0]
The information contained in this electronic message is confidential. It is intended solely for the use of to whom it is addressed and others authorised to receive it. If the reader of this message is not the intended recipient you are hereby notified that any use, copying, dissemination or disclosure of this information is strictly prohibited and are asked to delete it immediately and notify the sender. If you require any further details please call +44 (0)330 088 9542

**Comment by GreenDavidA** [comment]
I don't know if you were able to get the Skype call from the other user or if you still need assistance. Do you need anything further from me?

**Comment by GreenDavidA** [comment]
I think I might have figured out why I couldn't get it to appear. After looking at the code, it appears that the plan list filters out active features, and I'm pretty sure that the feature that was missing was active at the time. I'll keep an eye on this to see if I observe it happening again.

**Comment by Arjy** [comment]
Thanks David, Sorry I haven't responded until now. The feature that was missing for us, was below the top 100 threshold and did not appear. Re-ordering the features so the inflight ones were at the top sorted the issue out. Active features have always appeared for us.

**Comment by navneetg-msft** [comment]
I have increased the limit to 300, hopefully that will be useful in future. Please reopen the issue if you see any problems.
