### ISSUE TITLE
Feature Request: Timeline view of EPICs for all or selected Areas under a Project

### ISSUE THREAD

**Issue by amit-sunkuru-imaginea** [microsoft/featuretimeline#210]
1. We have one big team defined under a root AreaPath working under one common Sprint/Iteration. The team is organized into various Sub-Areas under the root AreaPath. The Portfolio Plan can shows a timeline view for all or selected EPICs under the root AreaPath's team though it currently cannot show the sub-Areas as horizontal swim lanes like sub-teams alongside the corresponding EPICs.
2. EPICs in our case can span multiple Sub-Areas (teams) under the root AreaPath in which case the Portfolio Plan's timeline view could flag this or if possible show it as an overlap across the swimlanes.
Delivery Plans extension is surely capable of doing (1) though it expects parallel Iterations to be set up for each Sub-Area

**Comment by mzdimal** [comment]
We have a similar requirement. It would be nice if this add-in could simply allow you to choose a team backlog and visualize all Epics in that backlog.
