### ISSUE TITLE
Project Access Issues

### ISSUE THREAD

**Issue by awentzel** [microsoft/featuretimeline#211]
**Describe the bug**
I'm the organization owner for my Azure DevOps account.  Someone has installed the Portfolio Plans / Feature timeline extension.  Now it's showing up for all projects.  Why does the installation default to all projects?  Defaulting to all projects feels backward.  The extension should activate on the project for which the user installed the extension, and other projects should be able to opt-in at their convenience.

How do I remove this extension from specific projects in the meantime?

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari
[x] All

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![Annotation 2019-09-04 084550](https://user-images.githubusercontent.com/16669785/64271757-bf653800-cef2-11e9-8acb-76510d745d4a.jpg)

**Comment by danhellem** [comment]
This is by design as portfolio plans will span across multiple projects. Also, the way extensions work with Azure DevOps is the extension is installed at the organizational level. They do not have a concept of extensions being installed at the project level.
