### ISSUE TITLE
"Portfolio Plans (Beta)" Doesn't appear under Boards

### ISSUE THREAD

**Issue by DIMKokan** [microsoft/featuretimeline#212]
I have the **Feature Timeline** and **Epic Roadmap** tabs on my backlog, but I don't have the **Portfolio Plans (Beta)** option under boards in the navigation menu.

I'm running Azure DevOps Server Version 17.143.28912.1
The extension's page mentions it works with Azure DevOps Server 2019, but the requirements list includes Azure DevOps Services.

Is portfolio plans only supported in Azure DevOps cloud?

**Comment by danhellem** [comment]
Checking with engineers to see if it will work on-prem or not. I believe you need to be on 2019+ and have the Analytics Service running as well. Standy by

**Comment by DIMKokan** [comment]
Thank you!
Just FYI - 
I'm running 2019.0.1 patch 1.
I have the analytics service running.

**Comment by danhellem** [comment]
It turns out this is by design for us. We are leveraging a feature that is only present in the service and is not yet available on-prem
