### ISSUE TITLE
Ability to disable Portfolio Plans (Beta) 

### ISSUE THREAD

**Issue by kavyafatehpuria** [microsoft/featuretimeline#213]
**Describe the bug**
Hi, I am the Product Manager for Azure DevOps for my organization (S&P Global). I have been reviewing this extension to enable for my organization and while the Feature Timeline and Epic Roadmap are great boards, we do not have much use for the Portfolio Plans (Beta) board. If we do show this board it will end up creating more noise than value for us. 

Is it possible to hide this board when enabling this extension so that users in my organization only get access to Feature Timeline an Epic Roadmaps?

Thanks in advance!
**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
We don't have any plans to disable the hub from the extension. The code is all open source, so you are welcome to fork the code, remote the Portfolio Planning Hub from the manifest, and publish your own version of the extension

**Comment by kavyafatehpuria** [comment]
Hey Hellem

I have a follow up question for this – if we do publish our version of the extension, would that mean that any future updates to the extension will not flow through for us?

Regards
Kavya Fatehpuria
Agile Tools Product Manager
• +91 9717810170
[cid:image001.png@01D1BABD.350A5570]
