### ISSUE TITLE
Azure DevOps Server 2019  can't open the web page

### ISSUE THREAD

**Issue by zhangwk02** [microsoft/featuretimeline#214]
**Describe the bug**
click the  button,but can't open 。response code 404
![image](https://user-images.githubusercontent.com/38233062/64578518-3ba7c180-d3b2-11e9-89ec-c9ffbff71836.png)

![image](https://user-images.githubusercontent.com/38233062/64578490-2337a700-d3b2-11e9-88c2-8d43a172c438.png)

**Browser**
Choose a browser

[ ] Chrome

**Version**
Azure DevOps Server 2019 
**Screenshots**
Status Code: 404 Not Found
response data :
{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}

**Comment by sghaugen** [comment]
Is there progress on this?  First I wasn't able to plan features (drag and drop in a sprint), now I just can not load the extension at all while using Chrome.  I am not using the server version of ADO.  My version of Chrome is Version 78.0.3904.70 (Official Build) (64-bit)
