### ISSUE TITLE
Progress tracking support for CMMI on Azure DevOPS

### ISSUE THREAD

**Issue by xkmarcink** [microsoft/featuretimeline#215]
It seems that for CMMI project progress tracking doesn't work. Same goes for drill down - URL points to Item, but immidiately redirects to backlog

**Comment by xkmarcink** [comment]
It might be connected with custom states

**Comment by ezambra** [comment]
Hi @xkmarcink 
Portfolio Plans supports any process type, including CMMi. We calculate progress based on the default work item type for the Requirement backlog level, which for CMMi would be "Requirement" work item type.

If you are not seeing progress values -either Completed Count or Effort-, please check that the items added to the plan contain "Requirement" work item types as descendants - based on parent-child link types-, and that they have values assigned for "Size" field.

We've also seen scenarios where the OData service does not return roll up values for the items even though they have descendants. Updating the item -e.g. updating the value for its start / target date- usually fixes the problem as the update will trigger a transform in the OData service.

Regarding drill down feature: If the work item type belongs to the Epics backlog level (e.g. "Epic" work item type), clicking on "Drilldown" will navigate to the "Epic Roadmap" pivot with the Epic pre-selected in the dropdown. For any other work item type, we default to the team's backlog.

Hope this helps, if not, please provide more information (e.g. screenshots, work item types you are using, process type) and we can look into it.

Thanks,
__Eduard.

**Comment by xkmarcink** [comment]
Relationships are fine, sizing sometimes is there sometimes not but it should not affect the progress tracking by count. Updating start/target date does nothing to overall state. 
![image](https://user-images.githubusercontent.com/40795697/64691537-2b1b4800-d493-11e9-9ac6-6eeb718b3477.png)

Drilldown for epics also doesn't work - at first it redirects to *`/_backlogs/ms-devlabs.workitem-feature-timeline-extension.workitem-epic-roadmap/teamname/Epics#68319` and then immidiately to 
`*/_backlogs/backlog/teamname/Epics/?showParents=true`

**Comment by ezambra** [comment]
Thank you for the details @xkmarcink . 

I'd need two additional data points to start the investigation. Could you please provide:
* Your account name
* Project id (or name) for epic 68319

If you don't want to share these values here, please feel free to send me an e-mail to eduard.zambrano@microsoft.com

Thanks,
__Eduard.
