### ISSUE TITLE
Feature enhancement suggestions

### ISSUE THREAD

**Issue by swonge** [microsoft/featuretimeline#217]
some suggestions
- allow sorting or manually position the order of Epic
- the tile is display based on start date and target date in Epics & Features instead of iteration path
- what's the usage of the dropdown (Epic, feature, PBI) at the top right hand corner?
- timeline always show on top, as the number of Feature grow, we lost of sight of timeline they belongs to
- the tile (feature tile) show the date/iteration they belongs
- different color selection on tile

**Comment by panuoksala** [comment]
I would like to see iteration start/end dates to be drawn as vertical lines this would help planning features inside iterations.

**Comment by bmarotta** [comment]
First two points are essential. Other ways, it is just a play toy and cannot be seriously used for tracking and presentations
