### ISSUE TITLE
Feature Timeline disappearing from collection, is there a new version that doesn't have the Beta Epic Roadmap.

### ISSUE THREAD

**Issue by Glenn-Gidlof** [microsoft/featuretimeline#218]
**Describe the bug**
Our enterprise instance of TFS is running v0.0.238 of the Feature Timeline extension and has been experiencing some collections having the Feature Timeline disappear.  We would like to try a newer version of this extension to see if it fixes the issue but we cannot deploy the current version that includes the Beta Epic Roadmap.  Any beta cannot be deployed at an enterprise level for us.

Is there a version available that does not include the Beta?

**Browser**
Choose a browser
[X] IE11
[ ] Chrome
[X] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[X] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
no sorry, the beta of the porfolio hubs is part of the features timeline. You are welcome to fork the the repo and take out the Portfolio Hubs from the manifest and deploy on your own

**Comment by Glenn-Gidlof** [comment]
Is there an available download of a prior version w/o the beta but later than the 0.0.238 version we currently have installed.

**Comment by Glenn-Gidlof** [comment]
Or do you have any suggestions on why Feature Timeline disappears from some of our collections?
