### ISSUE TITLE
Epic Roadmap fails with <<)>>

### ISSUE THREAD

**Issue by wpschaub** [microsoft/featuretimeline#219]
**Describe the bug**
In one of our projects the Epic Roadmap extension has started to fail with the error <<)>>, as shown below.

![image](https://user-images.githubusercontent.com/12176555/65356093-6e1e9f00-dba8-11e9-93a9-9d43d6ccbb85.png)

**Browser**
Choose a browser
[X] Edge
[ ] Chrome
[X] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/12176555/65356142-8c849a80-dba8-11e9-9f4d-9b2412bb7b8d.png)

**Comment by awittrock99** [comment]
I am having the same issue with Chrome.  But others on my team are not seeing the same issue (using Chrome).   In reviewing other trouble shooting options, it stated to review the Console details to confirm if there was an error.  Failed to load resource: the server responded with a status of 404 (Not Found).  Any assistance or additional direction on how to resolve would be appreciated.  Thanks.
