### ISSUE TITLE
Error when trying to select an Epic Roadmap "Object doesn't support property or method 'from'"

### ISSUE THREAD

**Issue by sullise** [microsoft/featuretimeline#220]
When you try to select an Epic Roadmap you get an error Object doesn't support property or method 'from'.  This is ADO 2019.1 Server.

**Comment by sullise** [comment]
![2019-09-24_14-27-59](https://user-images.githubusercontent.com/55762327/65541034-85c49300-deda-11e9-9a3f-9dc757351dac.jpg)

**Comment by StephanieMI** [comment]
Was the root cause of this ever found? I am seeing this same error on my Epic Roadmap.
