### ISSUE TITLE
Is the latest on market place?

### ISSUE THREAD

**Issue by srinilakshmi** [microsoft/featuretimeline#221]
Hi,

I recently worked with my org and got this installed on our org. but the screenshots are looking way better than the product and epic road map never worked. Is there a different version that is for screenshots?

Thanks,

**Comment by danhellem** [comment]
Actually the screen shots are older than the current in the marketplace. Can you send some screen shots of what you are seeing?

**Comment by srinilakshmi** [comment]
Thanks for your reply.
Actually, not only that few issues am facing are

1. Epic roadmap do not load
2. Any configuration can be done for the making color adjustments, like color change and filling in the items?
3. in screenshot I see sprints as dropdown here it is a number.

And attached is the screenshot
![GITGUB](https://user-images.githubusercontent.com/56143081/66275074-0ed0b800-e853-11e9-83dc-9b31a433e827.jpg)

**Comment by danhellem** [comment]
1) Are you getting any kind of errors for Epic Roadmap?

2) No sorry, no configuration for colors

3) I believe this is by design now

**Comment by srinilakshmi** [comment]
Am not getting any error but keep spinning for longer time.
