### ISSUE TITLE
Feature Request - Feature Timeline and Epic Roadmap - Linking to Other Projects

### ISSUE THREAD

**Issue by grubster8** [microsoft/featuretimeline#229]
Hi,
We have a Main Board that is hosting our Epics.  We then link features to the Epic.  We link features from Multiple Boards and Projects.  It seems that both the Epic Roadmap and Feature Timeline do NOT show features that exist in different projects\Area Paths.  Can this be fixed?

**Comment by IvoBliznakov** [comment]
+1
