### ISSUE TITLE
Feature request: epic timeline

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/featuretimeline#23]
Hi,

This is a great extension. Are you planning to allow for an epic timeline similar to what it does for features? We'd like to be able to see our epics and control how they span from start iteration to end iteration.

**Comment by navneetg-msft** [comment]
At this time it is not on the radar, did you try Epic Roadmap pivot? There you can see the progress of entire Epic across multiple teams, does that satisfy your requirement?

**Comment by jdshkolnik** [comment]
I did try it but no, it doesn't really satisfy this requirement (nor does it really work well at all yet).

Your extension has something vital which deployment plans don't...explicitly spanning multiple sprints (although it'd be great if I could set it without dragging.) We'd like to do that for epics same way you enable us to do for features.

**Comment by navneetg-msft** [comment]
Thanks I will think about it.
Can you share specific feedback about Epic Roadmap on what does not work at all?

**Comment by navneetg-msft** [comment]
Thanks for your feedback.
Closing as we shipped a feature where you can set start/end iteration without dragging it. 
At this point there is no plan to have epic displayed in calendar view. We will reconsider if more people ask for it.
