### ISSUE TITLE
Epic Roadmap

### ISSUE THREAD

**Issue by MAFE62** [microsoft/featuretimeline#235]
**Describe the bug**

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari
Edge

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/57509951/68438705-98451400-018a-11ea-85fe-40fd8d1637c7.png)

I tried with Epic Roadmap… it was working OK when there was two Epics.. Now I have 6 Epics and the following message is arising:

"Expecting constant value. The error is caused by <<)>>"

**Comment by craigeddy** [comment]
I am experiencing this issue as well. Near as I can tell, there are no Epic work items that have `)` in their title (at least in the team project where I see this crop up)

**Comment by CMB87SALF** [comment]
We are also getting this issue.

Currently have 7 epics, so I don't know when it started, but I do know it was working fine when I demoed the feature with just one.

One of the epics contains an & and another contains a -, the rest have no special characters. None contain a ).
