### ISSUE TITLE
Epic Roadmap (beta) appears when Epics are disabled.

### ISSUE THREAD

**Issue by SEnglishSMP** [Microsoft/featuretimeline#24]
I have the Feature Timeline and Epic Roadmap extension (previously just the Feature Timeline) installed.  Today I notice a new "Epic Readmap (beta)" button.  We have Epic work items disabled and the backlog configured to only show backlog items and features (not the epic level).  Given that epics are off (more precisely the epic backlog level is off), the Epic Roadmap should not appear.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome - Version 67.0.3396.99 (Official Build) (64-bit)
[ ] FireFox
[ ] Safari

**Version**
[x] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by navneetg-msft** [comment]
Thanks for reporting the concern. At this point there is no good way to hide the tab when Epics are disabled. I can show a message when user switches to the tab, but I am not sure if that will help.
Please let me know.

**Comment by SEnglishSMP** [comment]
Another way to address the issue would be to put the new tab only on the Epic backlog.  At the same time, you could put the Feature Timeline only on the feature backlog.  That way, when I'm looking at the feature backlog, I can switch to the timeline.  When I'm looking at the Epic backlog (which requires it to be enabled), then I can switch to the Epic Roadmap.

It always seemed strange to me that that when I'm looking at the requirements level, the tab for Feature Timeline shows up.  I'm not at the feature level, so why is the tab there?  

Having each tab show only at the appropriate level would address this issue.

**Comment by jdshkolnik** [comment]
If you can't hide the tab, can you at least hide the dropdown?

**Comment by navneetg-msft** [comment]
I just pushed an update which will not show the dropdown when team do not have any epics.
Sorry for late response, I am little busy these days.
