### ISSUE TITLE
Portfolio plan is visible across entire DevOps instance

### ISSUE THREAD

**Issue by dmuscat** [microsoft/featuretimeline#240]
It seems that no matter which Project I open in our DevOps instance, they all can see every Portfolio Plan. This doesn't make sense. A Portfolio Plan should only be visible to the projects which have been included in the plan.

For example, If I add an Epic from Project A and an Epic from Project B to a Portfolio Plan, I would expect the Portfolio Plan to be visible in both these Projects. However, the Plan is also visible in Project C and D, even though none of their Epics are included in the Plan.

This poses a security risk as we have many teams on many different portfolios within the same DevOps instance.

**Comment by djerghiuta** [comment]
Having the same problem. Installed the extensions, and users got excited about the functionality. I already see lots of plan, including lots of "xyz testing" from people exploring the functionality. We are in a large Azure DevOps organization, as adoption grows I don't know how we'll deal with the clutter.
Some good news though - if I open a plan, data is still filtered by my permissions, so it does not appear to be a security issue.
We need though some kind of usability improvement for the home screen, with the list of plans. Could they be filtered by the project I'm currently in (i.e. only plans that include data from my project would be listed)?

**Comment by Xizindar** [comment]
Similar issues that my organization faces and it's worse than you think... anyone can delete anyone else's Portfolio Plan.  See issue opened up months ago:  https://github.com/microsoft/featuretimeline/issues/206#issue-486602026

**Comment by calvinmichel** [comment]
Is this issue being looked into?  The other features our teams can use, but I will have to send out a communication for users NOT to use Portfolio Plans until this has been fixed.
