### ISSUE TITLE
Portfolio Plan can't add items in bulk

### ISSUE THREAD

**Issue by lfssp** [microsoft/featuretimeline#242]
I am trying to use portfolio plan to create a plan with 25 epics and a lot of features.
Having to add one by one doesn't seem to be a clever option as it takes a lot of time. We should be able to add a bunch of epics/features in the same time into the plan.

**Comment by oglio123** [comment]
I really like it and I have the same issue as @lfssp

**Comment by StevenSparcs** [comment]
As temporary workaround: shift click allows you to add them all at once (both epics and features)
