### ISSUE TITLE
Feature Timeline not showing all sprints

### ISSUE THREAD

**Issue by ursulich** [microsoft/featuretimeline#248]
Hello, please see: https://developercommunity.visualstudio.com/content/problem/821144/feature-timeline-view.html

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
