### ISSUE TITLE
Plan view not displaying upcoming sprints

### ISSUE THREAD

**Issue by ursulich** [microsoft/featuretimeline#249]
**Describe the bug**

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari
X Edge

**Version**
[x
![Azure Devops Plan View](https://user-images.githubusercontent.com/59741710/72171775-82212300-3388-11ea-952c-d2c4679af455.PNG)
 ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
