### ISSUE TITLE
Portfolio Plans doesn't account for unparented/orphaned work items

### ISSUE THREAD

**Issue by ahsanzia2010** [microsoft/featuretimeline#250]
Portfolio plans doesn't give you a complete picture of a project when there are unparented or orphaned features or user stories in the project. When working on the sprint backlog you add a new user story, it is created without any link to a parent. You have to specifically add a parent link. But if you don't this user story is not accounted for in the portfolio plans for this project. Same is true for the features.

Any plans to show unparented or orphaned user stories and feature under the portfolio plans? Or at least put a warning message out that you have unparented or orphaned work items in a project. 

Thanks!

**Comment by ahsanzia2010** [comment]
Does anyone even look at the issues reported here? Is there a way to bring this to MS attention quickly? Thanks!

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
