### ISSUE TITLE
Add items - Show Search field instead of select project

### ISSUE THREAD

**Issue by ooeler** [microsoft/featuretimeline#252]
**Describe the bug**
I click on add items then the side view opens. Afterwards I click on "Select a project". Then the search field is displayed. Now I need to click into the search field.

**Suggestion** Directly show the search field.

**Browser**
Choose a browser
[x] Chrome

**Version**
[x] Azure DevOps/VSTS

**Screenshots**
![image](https://user-images.githubusercontent.com/58941536/73068245-102dfb00-3eab-11ea-9b32-f740734bd3ec.png)

![image](https://user-images.githubusercontent.com/58941536/73068267-220f9e00-3eab-11ea-9636-246a27269211.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
