### ISSUE TITLE
Add items - Possibility to pin a project as a favorite

### ISSUE THREAD

**Issue by ooeler** [microsoft/featuretimeline#253]
**Describe the bug**
When I do the portfolio management then I normally work with a handful projects. It would be very beneficial if I could mark my often used project as favorites.

**Browser**
Choose a browser
[x] Chrome

**Version**
[x] Azure DevOps/VSTS

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
