### ISSUE TITLE
Epic timeline question

### ISSUE THREAD

**Issue by kpraeger** [microsoft/featuretimeline#254]
I am looking for a view similar to Feature Timeline, except instead of the feature going across horizontally, I would like a list of each developer and what they are working on. Does this exist or is there a way to adjust this to make it work?

I've also asked a question on StackOverflow here: https://stackoverflow.com/questions/59974900/in-azure-devops-is-there-a-way-to-list-all-work-items-by-developer-assigned-to

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
