### ISSUE TITLE
Portfolio Plans visible on Server 2019

### ISSUE THREAD

**Issue by jespersh** [microsoft/featuretimeline#255]
**Describe the bug**
As asked in #127, then Portfolio Plans isn't supposed to be visible on Server 2019, but I found that it is visible in Work Items drop down menu.
The screenshot shows a portfolio plan I created before it got hidden/disabled.

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[X] FireFox
[ ] Safari

**Version**
[X] Azure DevOps Server 2019

**Screenshots**
![image](https://user-images.githubusercontent.com/1004198/73430136-9d56d100-433d-11ea-9da0-68344321cd30.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
