### ISSUE TITLE
URGENT: Some Work Items are excluded as they are in iterations that the current team does not subscribe to.

### ISSUE THREAD

**Issue by alexanderbrooks** [microsoft/featuretimeline#256]
**Describe the bug**

**Browser**
Choose a browser
[ ] IE11
[X ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
If applicable, add screenshots to help explain
![screenshot-2](https://user-images.githubusercontent.com/9052333/73564770-51d02000-442e-11ea-966c-746366a27255.png)
![screenshot-1](https://user-images.githubusercontent.com/9052333/73564771-51d02000-442e-11ea-971c-cb20580f3817.png)
![sprintscreen-3](https://user-images.githubusercontent.com/9052333/73564772-51d02000-442e-11ea-9c10-642cc29849ab.png)

 your problem.

I have been using Azure DevOps for sometime now and I've never encountered this issue before. For some reason. Some Epics and Features are not showing up in the Feature Timeline and I receive the the following message from Epic Roadmap when I select an Epic that is not shown in the feature timeline. **"Some Work Items are excluded as they are in iterations that the current team does not subscribe to. Click here to see the details"**

**Comment by barbetb** [comment]
I have exactly the same issue, and no idea how to resolve it. In my case the backlog column "mapping" does not work. So you set in team settings "Backlog iteration" to a certain iteration, but then in the actual few it will still complain it is not there for items in that iteration. It is very confusing. Is there a fix or solution coming?

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
