### ISSUE TITLE
Full screen - FeatureTimelineGrid

### ISSUE THREAD

**Issue by Jerokun** [microsoft/featuretimeline#257]
Currently the max width is set at 60% which is a very bad design idea in my honest opinion. The height is also fixed at 300px.

It would be nice if the width was set to use the full screen size and the height should adjust based on how much space is needed (to max full-screen).

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
