### ISSUE TITLE
Support more than 255 characters on multi-line fields

### ISSUE THREAD

**Issue by vinijmoura** [microsoft/featuretimeline#259]
**Describe the bug**
When I apply Default Value or create a rule to multi-line fields (Description, Acceptance Criteria), I'm limited to 255 characters. I want to apply HTML pattern when I create work Item.

**Version**
[ X ] Azure DevOps/VSTS

**Screenshots**
On Inherited Process (Default Value)
![image](https://user-images.githubusercontent.com/8333012/74057702-413a1f80-49c3-11ea-864a-94b9f52cb37f.png)

On Process Rules
![image](https://user-images.githubusercontent.com/8333012/74057741-51ea9580-49c3-11ea-9ee2-c8259f92649d.png)

**HTML Pattern example**
<b style="font-weight:normal;"><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13.999999999999998pt;font-family:Poppins,sans-serif;color:#434343;font-weight:400;">Background and current conditions:</span></p><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Poppins,sans-serif;color:#434343;font-weight:400;">Percebemos que &lt;fato&gt; está impactando &lt;indicador de Biz ou Customer&gt;</span></p></b><div><br></div><br><b style="font-weight:normal;"><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13.999999999999998pt;font-family:Poppins,sans-serif;color:#434343;font-weight:400;">Root cause:</span></p><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Poppins,sans-serif;color:#434343;font-weight:400;">&lt;exercício de até 5 por quês&gt;</span></p></b><div><br></div><br><b style="font-weight:normal;"><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;">Goals:</span></p><p dir=ltr style="margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Poppins,sans-serif;color:#434343;font-weight:400;">&lt;target dos indicadores do problema&gt;</span></p></b><br><br>

**Comment by MartinaMS** [comment]
filed here: https://developercommunity.visualstudio.com/idea/911327/set-default-value-on-html-fields.html
