### ISSUE TITLE
Cannot do anything with the extension except to add a feature

### ISSUE THREAD

**Issue by anthony-gregg** [microsoft/featuretimeline#260]
**Describe the bug**
The user is not able to "Add a Field Criteria", "Add a team" or "Add a Marker" as they do not have enough permissions apparently. I have read the Read Me notes and the only permissions it mentions that they need is the ability to Read Analytics, which they do have. So the question is, what permissions explicitly do they need to manage this extension? The enclosed screen shot shows the error message. I am trying to give them the needed permissions, but there is no clear information on what permissions they need. They are not a Project Admin and I will not be giving them that permission since they do not need it. Can you please outline what permissions are needed to manage all capabilities of this extension.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![Plan Extension issue](https://user-images.githubusercontent.com/23386642/74277970-09dab400-4cde-11ea-98bd-738abc0f8353.jpg)

**Comment by KimPlausible** [comment]
This is not related at all to the Feature Timeline extension, but rather the Delivery Plans extension. Is the user using a Stakeholder license?

**Comment by anthony-gregg** [comment]
Hi,

Thank you for your response, I appreciate it. Good catch and yes, I did see that after the fact and we did fix the problem once we discovered that. I was told by the user the issue was with this extension, but discovered that it was nothing to do with this extension. I apologise for that.

Thanks again for your response.

Anthony
