### ISSUE TITLE
When I select my Portfolio Plan, an empty white screen is displayed. I can open other Portfolio plans however and have all options available.

### ISSUE THREAD

**Issue by ofriel** [microsoft/featuretimeline#261]
**Describe the bug**
When I select my Portfolio Plan, an empty white screen is displayed. I can open other Portfolio plans however and have all options available

**Browser**
Choose a browser
[ ] IE11
[x ] Chrome
[x] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
