### ISSUE TITLE
Features sticking to iteration when removed

### ISSUE THREAD

**Issue by tparis0022** [microsoft/featuretimeline#262]
The Feature Timeline is displaying Features in an Iteration that has been previously assigned to an Iteration Path but then moved to the General Backlog. However, the Feature is sticking on the Feature Timeline and I can't seem to find a workaround to remove it from appearing the Feature Timeline.

None of the children items within the Feature are assigned to any Iteration Path and are assigned to the General Backlog.

How can I remove these from the Feature Timeline view?

[Feature Timeline sticking to historic Iteration Path.pdf](https://github.com/microsoft/featuretimeline/files/4261231/Feature.Timeline.sticking.to.historic.Iteration.Path.pdf)

**Comment by crmckenzie** [comment]
We're running into this too

**Comment by jburrell42** [comment]
This is a big problem as I can remove features from my timeline that might have been dropped on by accident.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
