### ISSUE TITLE
Is portfolio plans available on premise (TFS)?

### ISSUE THREAD

**Issue by Ariel-W** [microsoft/featuretimeline#263]
Hello,
Is it correct that portfolio plans is not available on TFS On Premise version?
If so - will it be available in the future?

Thanks,

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[X] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
