### ISSUE TITLE
Stop using static references to Work Item Type names in the UI (Feature and Epic)

### ISSUE THREAD

**Issue by ghost** [microsoft/featuretimeline#264]
Azure DevOps allows you to configure your own Process, including your own Work Item Types and backlog levels. 

However, this product uses Work Item Type names in their product titles (and in the UI): they are called 'Feature Timeline' and 'Epic Roadmap'. 

This creates a problem when working with other Work Item Types in your backlog levels. For example, if you use 'Initiatives' instead of 'Epics', it is still called 'Feature Timeline' (instead of 'Initiative Timeline'). 

This might sound trivial, but for a large enterprise, who invested a lot in making all stakeholders 'speak the same lingo' this is very annoying. So please either dynamically generate the titles in the UI, or use generic names that do not include any static reference to a work item type name.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
