### ISSUE TITLE
Shift multiple items simultaneously

### ISSUE THREAD

**Issue by mywyb2** [microsoft/featuretimeline#265]
On Portfolio Plans, I would like to select multiple Epics or Features and drag them to shift their schedules backwards or forwards simultaneously.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
