### ISSUE TITLE
Portfolio Plan: Project remains after epics are removed

### ISSUE THREAD

**Issue by nickdodd79** [microsoft/featuretimeline#267]
**Describe the bug**
We added epics to a portfolio plan that spans 4 projects. We then consolidated a load of epics from 2 of those project so we only had 3 projects. However, the 4th project that we still want to use, but has no epics work items, is still displaying in the plan. We have tried several way of removing it from the plan, but nothing seems to work. 

Our assumption is there is still some link between the plan and the epics that did exist in that project. When the epics were removed, the links remained.

**Browser**
Choose a browser
[ ] IE11
[ x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
This is the lane for the project with no epics. It is an never ending lane of nothing.

![image](https://user-images.githubusercontent.com/28779139/76805833-06ce6880-6834-11ea-8454-67039c3e4f9b.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
