### ISSUE TITLE
Parent work item closes when closing child work item

### ISSUE THREAD

**Issue by jonest** [microsoft/featuretimeline#268]
**Describe the bug**
If I open a feature in a modal from the feature timeline, then click on a child PBI to open that in a modal (which is above the feature), when I close the PBI to go back to the feature it's now closing the feature, too.

I noticed this with test cases when I opened a bug attached to the test case, too.

I was directed to report this here by the DevOps team:
https://developercommunity.visualstudio.com/content/problem/826595/parent-work-item-closes-when-closing-child-work-it.html

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[x] FireFox
[x] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
