### ISSUE TITLE
keep getting an error message that the Feature Timeline failed to load Azure DevOps Services

### ISSUE THREAD

**Issue by K981900** [microsoft/featuretimeline#269]
I was able to pull up the Feature timeline view a couple of times, but now all I’m getting is the message below….
![image](https://user-images.githubusercontent.com/62400469/77105204-3d021880-69eb-11ea-9483-2edb4ec7ea67.png)

Feature timeline and Epic Roadmap by Microsoft DevLabs failed to load.Learn More about this extension, including available support options.

**Comment by dkelchne** [comment]
We are having the same issue on Epic Roadmap.  Please advise a fix.  Thank you.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
