### ISSUE TITLE
Using backlog Feature Timeline  view - dates don't honor user settings

### ISSUE THREAD

**Issue by TheDarlek** [microsoft/featuretimeline#271]
When using Feature Timeline in backlogs the date format is mm/dd which is not either my organization setting or my personal one and it is true for other users as well.

I have seen this consistently in FireFox, IE, Chrome and Edge. Doing a cache reload, <shift><refresh> doesn't help either.

I would really appreciate a solution or workaround if you know of one please.

![image](https://user-images.githubusercontent.com/63339420/78759114-39065c80-79d3-11ea-8d05-c3aefdea6d51.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
