### ISSUE TITLE
Iteration/Sprint dates are a day off from the defined date in Project Settings

### ISSUE THREAD

**Issue by Glenn-Gidlof** [microsoft/featuretimeline#272]
The dates displayed in Feature timeline for the sprint are a day behind what is defined in the Project setting for that iteration.
The iteration date as set in Project settings are 4/08/2020 - 4/21/2020

![image](https://user-images.githubusercontent.com/34252153/80130347-4718b900-854d-11ea-9f49-3e11cbc295eb.png)

And when viewed in Feature Timeline they are showing up as one day earlier 4/07/2020 - 4/20/2020

![image](https://user-images.githubusercontent.com/34252153/80130243-1f295580-854d-11ea-971d-b92ba2d29477.png)

This has been reported as an issue for our users when using Feature Timeline for planning.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
