### ISSUE TITLE
Portfolio Plan (beta) dates 

### ISSUE THREAD

**Issue by kondvilkarrakesh** [microsoft/featuretimeline#273]
Hi,

What dates does Portfolio plan use to align the epics/features. I observe that even after providing Starting Date and Target Dates it did not pic those dates.

I will be importing a set of epics & features and I would like the portfolio plan to honour those dates.

Please can you let me know what field to use for this.

**Comment by v-namav** [comment]
Hi,
How can we mark PortFoli Plan as favorite? 
Thank you!

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
