### ISSUE TITLE
Epic Roadmap - Not picking up backlog items correctly

### ISSUE THREAD

**Issue by Geraint87** [microsoft/featuretimeline#275]
**Describe the bug**
The Team backlog iteration doesn't seem to be picked up correctly.
* In Epic Roadmap, Features have to be in a set iteration, or if I clear that iteration start/end date, it will pick up the iterations of its child items
* Child items on the backlog are not appearing. It shows 1 User story, and an empty backlog (screenshot). There are 6 other stories in the backlog
* Warning appears in the banner that there are some items in backlogs that are not subscribed to. The Iteration it suggests adding is that backlog iteration. You can't add that in the Team Settings because you can only add iterations that are children of the default backlog.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/5928208/81699915-e1d72a00-945f-11ea-9f51-6a9806d1e869.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
