### ISSUE TITLE
Epic & Feature Timeline taking too much time to load

### ISSUE THREAD

**Issue by Kumar3010** [microsoft/featuretimeline#276]
we have added feature timeline into our devops but the page gets struck at "Loading Loading" as shown in the screen shot. could you please let us know what could be the issue.

**Browser**
Choose a browser

[ ] Chrome

**Version**
[ ] Azure DevOps/VSTS

**Screenshots**
![image](https://user-images.githubusercontent.com/42348194/82025601-33292880-96af-11ea-8714-27a8943b1fb6.png)

**Comment by carloreggiani** [comment]
The same also for me.... but let me ask: this project is still alive? 
And if not, it is not clear if this GREAT functionality will be an AzureDevops build in feature, any info?

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
