### ISSUE TITLE
No way to filter Feature Timeline view

### ISSUE THREAD

**Issue by zerox1212** [microsoft/featuretimeline#278]
**Describe the bug**

We often have several epics active at one time that are not related to each other, but there is no way to filter the view. Every feature and parent epic are always shown. Filters on the backlog also are not applied to feature timeline view.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by apurvashukla** [comment]
Agree. It would be a very essential feature to filter the Feature timeline based on epics, or assignments to present different kinds of views.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
