### ISSUE TITLE
Is this actively being devloped?

### ISSUE THREAD

**Issue by zerox1212** [microsoft/featuretimeline#279]
No merges since October 2019 and readme says this project originated from a hackathon. Is there any plan to actually continue development on this?

Feature timeline is one of the only good ways to visualize our work in DevOps.

If anyone has an alternative in Marketplace please post it here.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
