### ISSUE TITLE
Epic Roadmap takes a long time to load and then displays Test Cases not Epics

### ISSUE THREAD

**Issue by AliciaAnderson** [microsoft/featuretimeline#280]
**Describe the bug**
When I click on Epic Roadmap, it takes about a minute to load.   When I click on the drop down list, it takes 15-30 seconds to respond.   A huge list displays but they are not Epics.  After further review, it is displaying
![EpicRoadmap1](https://user-images.githubusercontent.com/66956001/84664123-b07cce80-aee3-11ea-8792-bf26b2229fd3.png)
![EpicRoadmap2](https://user-images.githubusercontent.com/66956001/84664124-b1156500-aee3-11ea-8bb6-32c2f5901126.png)

 Test Cases!  See screenshots.

**Browser**
Choose a browser
[ ] IE11
[X ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
