### ISSUE TITLE
Epic Roadmap is broken => Expecting constant value. The error is caused by «)»

### ISSUE THREAD

**Issue by chrizzo84** [microsoft/featuretimeline#281]
**Describe the bug**
When a Epic was deleted, we are getting an error "Expecting constant value. The error is caused by «)»".
As a workaround I restored the workitem. In my case, the workaround still worked because the work item was not deleted permanently. But what if it was deleted permanently?

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[x] FireFox
[x] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by samh1234** [comment]
I have the same issue, but I have restored all deleted Epics from the recycle bin - as far as I am aware no Epics have been permanently deleted. I still get the error. 
Other teams in my organisation have deleted Epics in the recycle bin, yet the Epic Roadmap works for that team.

Any comment or suggestion to resolve this issue very welcome!

**Comment by marcohevi** [comment]
Same issue here. Also unable to visualize, even after restoring.

**Comment by henwik-1** [comment]
Same issue here, the workaround of restoring work items is not feasible here, I have deleted them for a reason. :)

Browser
[x] Chrome
[x] FireFox

Version
[x] Azure DevOps/VSTS

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
