### ISSUE TITLE
Is there a limit on the number of epics shown in the Azure DevOps feature timeline?

### ISSUE THREAD

**Issue by MariaSamojlik** [microsoft/featuretimeline#283]
Is there a limit on the number of epics shown in the Azure DevOps feature timeline?

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
