### ISSUE TITLE
Epics and Features fail to be added due to target-date being read-only

### ISSUE THREAD

**Issue by kscarmardo** [microsoft/featuretimeline#284]
TF401320: Rule Error for field Target Date. Error code: ReadOnly, InvalidNotOldValue.

I do indeed have target date set to read-only once the feature/epic becomes active.  I've not looked at the source, but I'm guessing this plugin adjusts target date vs iteration assignment?

In my case I use target date as a "desired timeframe" whereas the date it's completed in an iteration is what I use for the actual completion time.  This facilitates reporting against Active work that's late as well as work Completed late.

![image](https://user-images.githubusercontent.com/8491366/88405417-d88a0800-cd94-11ea-81dc-41a97f1f5667.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
