### ISSUE TITLE
Cannot view Epics and Feature assigned to a state in Resolved Category on the Roadmap

### ISSUE THREAD

**Issue by Chintunie** [microsoft/featuretimeline#287]
An epic or feature which is assigned to a state in **Resolved** Category does not appear on the Roadmap.

In the following example, if a work item is assigned to **Validate** state (in **Resolved** category), it does not appear on the Roadmap.

![Resolved](https://user-images.githubusercontent.com/26616762/90251002-a97a2a00-de5a-11ea-9a3a-6b18d85d1d4a.JPG)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
