### ISSUE TITLE
Can you export timeline to other application?

### ISSUE THREAD

**Issue by Gliksme** [microsoft/featuretimeline#290]
I would like to be able to share the timeline with senior stakeholders - can the timeline be exported? Or would I need for all stakeholders to have access to DevOps?

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
