### ISSUE TITLE
Add Custom field to entities view

### ISSUE THREAD

**Issue by ofirt** [microsoft/featuretimeline#293]
**Describe the bug**
Is there any way to add custom fields to the features boxes,  just like the appearance of total points completed? For example, I would like to add the total story points .

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
