### ISSUE TITLE
Work items without dates get Start/Target dates assigned by the extension if selected

### ISSUE THREAD

**Issue by Donpampa** [microsoft/featuretimeline#294]
**Describe the bug**
Pick several features, create portfolio with them. Features without Start/Target dates get them auto assigned by the tool.
**Browser**
Choose a browser
[ ] IE11
[x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
