### ISSUE TITLE
Is this extension going to be supported? It provides unique view that is useful for many people. It is a shame to see the extension go dormant/stop.

### ISSUE THREAD

**Issue by Donpampa** [microsoft/featuretimeline#296]
**Describe the bug**

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by AntonyRobinson** [comment]
I spoke to Microsoft last week and they are releasing it as part of the core product and should be public preview within the next couple of weeks

**Comment by duncancoppedge** [comment]
Looks like it's available for preview now.
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-178-update#delivery-plans-preview 

> Azure Boards is an extremely capable product for planning and managing work at the team level. Many larger organizations would like to see a roadmap and timeline of work being done across multiple teams and projects, however, and Azure Boards is not as capable at this. Over the years we have attempted to solve this problem with a variety of third-party plugins and extensions, including the Delivery Plans extension. Unfortunately, these attempts have not fit the bill for many customers, and we continue to hear that they need better capabilities.

> Today we are happy to announce a public preview for Delivery Plans 2.0. We are taking the best concepts from the Delivery Plans extension and expanding them to provide a first-class roadmap and timeline solution natively in Azure Boards. The initial preview will include these features:
> 
>     Bringing Delivery Plans into the core product, rather than requiring an extension to be installed.
>     Enabling work items to span iteration boundaries.
>     Enabling drag and drop borders to show when a work item starts and ends.
>     Enabling stakeholders to view plans.
> 
> delivery plans
> 
> Although this is a good start, we have more to do. There are several other features currently in-progress that will enhance Delivery Plans 2.0 and make it a delightful road-mapping experience. These features will get released over the span of the next few sprints. We hope to have them completed by the end of 2020. These features include:
> 
>     Viewing rollup information to track the progress of child work items.
>     Tracking and visualizing work item dependencies across teams and projects.
>     Supporting more than 10 team backlogs on a plan.
>

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
