### ISSUE TITLE
feature roadmaps are all using the earliest sprint and showing it as the current sprint

### ISSUE THREAD

**Issue by ShawnTrent-BCI** [microsoft/featuretimeline#298]
We noticed this on the last day of the sprint, not sure if it is a bug or how the last day of the sprint is presented

**Browser**
Choose a browser
[ ] IE11
[x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[x ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by Rickm1970** [comment]
Currently seeing this problem. Was it ever resolved?

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
