### ISSUE TITLE
Blank screen in viewing plan

### ISSUE THREAD

**Issue by vpgalon16** [microsoft/featuretimeline#299]
Add or updates features and user story from azure dev ops
Go to Portfolio plans and when you click the plan the next screen become empty.
- It says loading portforlio plan...
![image](https://user-images.githubusercontent.com/19661958/96790942-13631100-1454-11eb-9bef-76cc1c3543cd.png)

- After that the empty screen appeared.

Any idea what's wrong why we can't see the features and user story in the plan?

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[x] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by WimKok01** [comment]
I have the same problem with 3 Portfolio plans
![Portfolio plan de werkplek](https://user-images.githubusercontent.com/47181909/117624798-98561380-b175-11eb-8bd7-a6d15e8ac31a.PNG).

what can i do to solve the error

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
