### ISSUE TITLE
Tally Effort(Story Point) for each sprint

### ISSUE THREAD

**Issue by JeanLiufromiTrellis** [Microsoft/featuretimeline#30]
Do you plan to add a total count of Effort(story points) for each sprint? It's a sum of effort(story points) of all the User Stories that go into a sprint. This feature improvement will be useful to show team velocity in the past as well as in planning to forecast how much capacity we would have left in comparison to our velocity, hence how many more user stories we could still pull in for that sprint .

**Comment by navneetg-msft** [comment]
Really good suggestion. I will consider it in next major update. Currently I am little busy in my day job, so can not give an ETA :).

**Comment by JeanLiufromiTrellis** [comment]
Thank you for the update. Look forward to it :)

**Comment by cmeyertons** [comment]
Second this.  @navneetg-msft are you accepting PRs?  I might try to take a stab at this.

The view would be different based on how progress is tracked:

Completed Efforts:
![image](https://user-images.githubusercontent.com/19917677/46535565-71bef600-c871-11e8-9f10-f5aa9c35ca1b.png)

Completed Stories:
![image](https://user-images.githubusercontent.com/19917677/46535624-a763df00-c871-11e8-9f0a-cf71a78af6cf.png)

**Comment by navneetg-msft** [comment]
@cmeyertons I am accepting PRs, please let me know if you have any questions about the code etc, I can give you a code walkthrough if that would help.

**Comment by arrayka** [comment]
We need this as well. It would be great to have an ability to select a data source for the sum.
For example, in our case we are interested in two data points: the team's capacity for the iteration (in hours), total sum of Estimated field from tasks and bugs in the iteration's backlog.
