### ISSUE TITLE
Portfolio Plans Feature Requests

### ISSUE THREAD

**Issue by lymedo** [microsoft/featuretimeline#300]
Please can the following functionality be added to Portfolio Plans:

1. Epic title and progress bar to be displayed on separate lines - this will enable more of the title to be visible on short Epics
2. A tooltip when the mouse is hovered over the title to display the full Epic title
3. Additional fields (like the sprint board) or at the very minimum add the child node from the area path so that we can see which team is delivering the Epic.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
