### ISSUE TITLE
Feature Timeline is not shown on Backlog/Board

### ISSUE THREAD

**Issue by neustupa** [microsoft/featuretimeline#301]
**Describe the bug**

Azure DevOps Server 2020 on-prem. After extension installation there is no tab labeled "Feature Timeline" or "Epic Roadmap" on Boards or Backlogs page.
The extension shows no error during installation.

Thanks for any help.

Kind regagrds,
Zdeněk Neustupa

**Browser**
[ X] Edge

**Version**
[X] Azure DevOps Server 2020

**Screenshots**
Screenshots attached.
![image](https://user-images.githubusercontent.com/43957815/100716327-d118e200-33b8-11eb-9a61-aa320575cea9.png)
![image](https://user-images.githubusercontent.com/43957815/100716374-e130c180-33b8-11eb-947c-c9eb48c058b8.png)

**Comment by LucianoAlvesMendonca** [comment]
i have same problem...

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
