### ISSUE TITLE
Plugin is not working on 2020 Azure Devops Server

### ISSUE THREAD

**Issue by Gerard-Roos** [microsoft/featuretimeline#302]
**Describe the bug**
When selecting the feature timeline tab there is an endless "circle of death". So it hangs.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[+] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by DIGIHOME-MK** [comment]
Also portfolio plans feature is missing on Azure DevOps Server 2020 Patch 2.
![portfolio plans bug](https://user-images.githubusercontent.com/8817166/104806535-7f95ac80-57d8-11eb-9cd4-6cf56b7fceff.png)

**Comment by KevinAppelBofa** [comment]
@ezambra  Is there any movement on getting an update to this extension and being able to provide the Portfolio Plans feature on the Azure Devops Onprem version? This is missing and a note it is only available for the devops services version

**Comment by timoabend** [comment]
Need Portfolio Plans as well on Azure DevOps Server 2020 and it's missing as @KevinAppelBofa shows.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
