### ISSUE TITLE
group by Teams in Portfolio 

### ISSUE THREAD

**Issue by HaivisionJF** [microsoft/featuretimeline#303]
If we build a portfolio in one Project, it would be great to see the division of Epics/Features based on teams. Now instead, there is just one giant column showing one Project but no teams.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
