### ISSUE TITLE
Expecting constant value. The error is caused by «)» 

### ISSUE THREAD

**Issue by lataal** [microsoft/featuretimeline#305]
**Describe the bug**
 Users can’t view the epic roadmap anymore, getting the error message ‘Expecting constant value. The error is caused by «)»’. 

Solution to recover the deleted epics is no longer valid, as they were deleted. Was this error fixed as it is known for a while?
We also went to the Network tab, started profiling a session, repro the issues, then stopped profiling the session and export ed as HAR. Let us knwo if this will help troubleshoot the issue.

**Browser**
Choose a browser
[ ] IE11
[X ] Chrome
[ X] FireFox
[ ] Safari

**Version**
[X ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by rcalaba** [comment]
Any progress on this issue ??? I am facing exactly the same problem.

**Comment by MungBurger** [comment]
Any progress on this issue ??? I am facing exactly the same problem.

**Comment by blubber89** [comment]
I have the same error. I can't use the suggested solution to recover deleted Epics because the Recycle Bin doesn't contain any deleted Epics

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
