### ISSUE TITLE
Portfolio Plans (Beta) taking too long to load

### ISSUE THREAD

**Issue by josefbicik** [microsoft/featuretimeline#306]
A portfolio plan in Azure DevOps fetching work items from a single project takes more than 3 minutes to load and display approx. 65 Epics.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari
[X] Microsoft Edge

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![portfolio_plans](https://user-images.githubusercontent.com/2089987/106784754-f9d58600-664c-11eb-97da-283c4e400175.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
