### ISSUE TITLE
Moving a feature does not update the feature's dates

### ISSUE THREAD

**Issue by Graham-Git** [microsoft/featuretimeline#307]
I have several teams using feature timelines to plot out their roadmaps.
A 'project manager' then has a query to pull out the sprint dates or iteration paths from ADO
If the teams drag their features on the feature timelines this is not reflected within the features
So then the PMs view from their query differs from the actual feature timelines/roadmaps.

Is it possible to pull out of ADO the actual start and end dates from the feature timeline ??

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
