### ISSUE TITLE
Can features be automatic be added to view if part of board 

### ISSUE THREAD

**Issue by clendene** [microsoft/featuretimeline#308]
Does this extension allow for "automated" addition of new features to the timeline view?  we use azure as a team project board and we are constantly adding /closing features and would love to not have to reselect "new features added to the backlog" each time.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
