### ISSUE TITLE
Rollup bugs (as well as child user stories) to parent features 

### ISSUE THREAD

**Issue by JeanLiufromiTrellis** [Microsoft/featuretimeline#31]
In current version of Feature Timeline extension, child user stories are automatically rolled up to their parent feature, which is a very useful plug in for status tracking. Would you plan to roll up child bugs to the parent feature too? Or at least provide an option? We have some bugs pulled under features and the effort were not properly tracked as user stories.

**Comment by navneetg-msft** [comment]
What is your Bugs settings ... this should just work if you have Bugs as Requirements but not as task.

**Comment by JeanLiufromiTrellis** [comment]
Will look into that. Thanks!

**Comment by navneetg-msft** [comment]
@JeanLiufromiTrellis please let us know if you have any more questions?

**Comment by navneet-g** [comment]
Closing due to no-response.
