### ISSUE TITLE
Epic drop down lists more than just Epics (making it pretty unusable) without type down search, filtering, etc.

### ISSUE THREAD

**Issue by johnrsanders** [microsoft/featuretimeline#310]
**Describe the bug**
I originally filed it as in product feedback, but that got closed: https://developercommunity2.visualstudio.com/t/epic-dropdown-in-epic-roadmap-view-is-not-filtered/1344145?from=email

Basically the simple drop down on the board view showing Feature timeline and epic roadmap shows all types of items, including bugs. its scrolls forever.

If I could filter, type down search, etc. it might be OK.
But since it's titled Epic, and is a drop down, I assumed it would be filtered to only Epics.
We actually have a bunch of Epics across our team, so type down search would also be a nice new feature additon

**Browser**
Choose a browser
New Edge

**Version**
ADO online

**Screenshots**
Screenshot in linked issue

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
