### ISSUE TITLE
Rename of plans

### ISSUE THREAD

**Issue by guestdj** [microsoft/featuretimeline#313]
Would be nice to have the ability to rename any plans as it can take a long time to setup a plan

**Comment by innanill** [comment]
We would like to see this ability as well.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
