### ISSUE TITLE
Question on Parent and Child Areas? 

### ISSUE THREAD

**Issue by gkmontgomery** [microsoft/featuretimeline#315]
When there is work in a child area, how does it show in the Parent Area? 

![image](https://user-images.githubusercontent.com/83686562/117096538-02faef80-ad2f-11eb-8015-ea24247f50f0.png)

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
