### ISSUE TITLE
Dates don't correspond to iteration dates

### ISSUE THREAD

**Issue by GreenDavidA** [Microsoft/featuretimeline#32]
**Describe the bug**
It appears that the dates for each iteration in the Feature Timeline are offset by one day. The end date of the iteration is one day too early.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/34946195/44281322-6b26e180-a225-11e8-9f30-b48620571d62.png)
![image](https://user-images.githubusercontent.com/34946195/44281369-8c87cd80-a225-11e8-8f73-24852c3a398a.png)

**Comment by navneetg-msft** [comment]
Thanks @GreenDavidA  for your contribution.

**Comment by gagidlof** [comment]
Hi navneetg-msft,

Will this changed be released in an update in the near future?  We are seeing the same date offset issue as described by the original poster.

Thanks,
Glenn
