### ISSUE TITLE
Some PortFolio Plans will not Load

### ISSUE THREAD

**Issue by WimKok01** [microsoft/featuretimeline#320]
Some off the Portfolio Plans will not load, and I have no ability to remove them.
What can i do to remove those Portfolio Plans

![Portfolio plan de werkplek](https://user-images.githubusercontent.com/47181909/117625463-55487000-b176-11eb-90d2-34fe26da00ec.PNG)

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by NatiNinja65** [comment]
I am also experiencing the same issue as WimKok01. I have the same browser and version as well. Some of my Portfolio plans will load while I have a few that won't.

**Comment by aspiringtfsguru** [comment]
Same also the same browser and version.

**Comment by aspiringtfsguru** [comment]
I was able to delete a plan that wouldn't load by using postman and Chrome dev tools. Here's how I did it:

1. Open dev tools, click on the network tab and try to load the portfolio plan
2. Make note of the document id; it'll be in guid format
3. Now, open postman and create a new DELETE request. The URL will look like this:  https://extmgmt.dev.azure.com/<DevOps Org>/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/Default/Current/Collections/PortfolioPlans/Documents/<Doc Id>
4. Add this header: */*;api-version=3.1-preview.1;excludeUrls=true
5. Now run the request in postman. Be sure to replace DevOps Org and Doc Id with values relevant to you.
6. Go back to portfolio plans. You'll still see the offending plan, but this time you'll be able to open it and click the delete button. 

After you've gone through this process you might need to refresh your browser cache.

**Comment by WimKok01** [comment]
Hello Steve, Thanks for jour comment. I have tried to do also, but a collague of mine ( Postman User) made a suggestion to do a clean browser approach ( or incognito), with this clean browser approach i was able to delete the Portfolio plans, so i didnot follow your steps, but i get my result trough another way .
For me: This issue can be closed.

**Comment by WimKok01** [comment]
Hello Steve,


Thanks for your feedback.
I recently went through your step-by-step plan in consultation with a Postman user.

The postman user indicated that it can also be easier if you use a clean browser or an Incognito session

We tried that and because of that we were able to remove the Portfolio plans

Kind regards

Wim

Van: Steve Landsaw ***@***.***>
Verzonden: woensdag 23 juni 2021 16:26
Aan: microsoft/featuretimeline ***@***.***>
CC: Kok, Wim ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/featuretimeline] Some PortFolio Plans will not Load (#320)


I was able to delete a plan that wouldn't load by using postman and Chrome dev tools. Here's how I did it:

  1.  Open dev tools, click on the network tab and try to load the portfolio plan
  2.  Make note of the document id; it'll be in guid format
  3.  Now, open postman and create a new DELETE request. The URL will look like this: https://extmgmt.dev.azure.com/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fextmgmt.dev.azure.com%2F&data=04%7C01%7Cwim.kok%40waternet.nl%7C134626bcffe841c65bb008d93652c3e9%7Cdc176db0cbcb4c4984e9efe31a545c55%7C1%7C0%7C637600551381348481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n8OEchaA8xufXTsiCF8%2FZrsvGox5us1UW2mqw8LKbYc%3D&reserved=0>/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/Default/Current/Collections/PortfolioPlans/Documents/
  4.  Add this header: /;api-version=3.1-preview.1;excludeUrls=true
  5.  Now run the request in postman. Be sure to replace DevOps Org and Doc Id with values relevant to you.
  6.  Go back to portfolio plans. You'll still see the offending plan, but this time you'll be able to open it and click the delete button.

After you've gone through this process you might need to refresh your browser cache.

-
