### ISSUE TITLE
featuretimeline does not support dashboard widgets or have unique link to created plans

### ISSUE THREAD

**Issue by vgangotri** [microsoft/featuretimeline#322]
**Describe the bug**
Hi,
I have created a portfolio plan using featuretimeline extension. I want to share the plan with customers.  I have facing the below issues and need solutions around it.

1. The Portfolio plan doesn't support adding on to the Dashboard as widget. When a plan is created, no unique link is available to point into the Dashboard or no separate widget for featuretimeline is available.
2. How we can generate a link to a plan to pass on to the customers?
3. How we can export the Portfolio plan into excel or some other way

**Browser**
Choose a browser
- Chrome

**Version**
Azure DevOps

**Screenshots**
No widget available for featuretimeline extension

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
