### ISSUE TITLE
When changing names of work items Portfolio Plan fails to load and becomes unusable

### ISSUE THREAD

**Issue by kateyjackson** [microsoft/featuretimeline#323]
**Describe the bug**
I have an existing Portfolio Plan and changed the name of several Epics included in the plan, and also changed the item type on some of the items. 

When returning to the Project Plan board, and opening the plan, I found that the page would not load. I am unable to delete the Project Plan or update it. 

**Browser**
Choose a browser
[ ] IE11
[ x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/80415252/123466346-3afb1200-d5bd-11eb-8f73-0d8c2378bb97.png)

**Console Output**
storage.live.com/Users/0xd4d42d0ddca19607/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24:1 Failed to load resource: the server responded with a status of 404 ()
ms.vss-features.ui-hub-content.es6.7wCgcQ5zU8kFI2YQ.min.js:1 Must use title or breadcrumb items + headerItemPicker
vss-bundle-view-v_IEthc6iahPk33OYOMRTVNwDAWF-tc8zMawPTAIQZzo=:587 Backlogs.Open.FromNavigation - ends
storage.live.com/Users/0xd4d42d0ddca19607/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24:1 Failed to load resource: the server responded with a status of 404 ()
storage.live.com/Users/0xd4d42d0ddca19607/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24:1 Failed to load resource: the server responded with a status of 404 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
Telemetry.ts:56 Creating a new PortfolioTelemetry instance.
Telemetry.ts:223 Creating a new AppInsightsClient instance.
storage.live.com/Users/0xd4d42d0ddca19607/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24:1 Failed to load resource: the server responded with a status of 404 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
react-dom.js:117 TypeError: Cannot read property 'url' of undefined
    at EpicTimelineSelectors.ts:79
    at Array.map (<anonymous>)
    at getTimelineItems (EpicTimelineSelectors.ts:57)
    at Object.getSelectedItem (EpicTimelineSelectors.ts:94)
    at Function.mapStateToProps [as mapToProps] (PlanPage.tsx:189)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleNewState (selectorFactory.js:52)
    at handleSubsequentCalls (selectorFactory.js:69)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector (connectAdvanced.js:26)
Bg @ react-dom.js:117
utils.js:225 uncaught at LoadPortfolio TypeError: Cannot read property 'url' of undefined
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:112362:41
    at Array.map (<anonymous>)
    at getTimelineItems (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:112341:28)
    at Object.getSelectedItem (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:112377:16)
    at Function.mapStateToProps [as mapToProps] (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:110063:51)
    at mapToPropsProxy (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:98728:92)
    at handleNewState (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:98588:26)
    at handleSubsequentCalls (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:98605:30)
    at pureFinalPropsSelector (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:98610:32)
    at Object.runComponentSelector (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.357/1571072031114/dist/PortfolioPlanning.js:98008:25)
log @ utils.js:225
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
dc.services.visualstudio.com/v2/track:1 Failed to load resource: the server responded with a status of 400 ()
DevTools failed to load SourceMap: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meCore.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meBoot.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
