### ISSUE TITLE
Updates require a browser refresh for others viewing

### ISSUE THREAD

**Issue by plynch99** [microsoft/featuretimeline#325]
**Describe the bug**
When a feature is moved or updated others viewing this screen on their own computer have to refresh their screen to see the change. Other components within ADO don’t require a screen refresh to see the update.

Is there a way to have others view see the updates on the timeline feature without having to do a browser page refresh?

**Browser**
Choose a browser
[ ] IE11
[ x] Chrome
[ x] FireFox
[x ] Safari

**Version**
[ x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
