### ISSUE TITLE
Track Progress Completed Count > Count includes Work Items in "Removed" state

### ISSUE THREAD

**Issue by frvanwyhe** [microsoft/featuretimeline#330]
The Portfolio Plans view is counting work items in "removed state" for the completed count. 

**Browser**
Choose a browser
[X] Edge Chromium
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
