### ISSUE TITLE
Unable to open Portfolio Plan

### ISSUE THREAD

**Issue by jandej** [microsoft/featuretimeline#332]
Create a portfolio plan and was working 100% but suddenly cannot open it. Console show the following errors:

![image](https://user-images.githubusercontent.com/225384/149327855-dd2c4da8-5ab4-4461-83d8-9b85dabe1e31.png)

**Comment by jandej** [comment]
Was able to see that it is trying to load a User Story, but the epic.iconProps object is undfined... at line 79 in EpicTimelineSelectors.ts

**Comment by michaelpfister** [comment]
Just ran into the same issue.
Two things may have caused the issue in our case:
- A user has started a drilldown on a portfolio plan epic
- Another user has changed the Issue type of a shown item from Epic to Story

When opening the portfolio plan now, it ends up in an empty page with the console errors shown above.
Thus we aren't even able to delete the plan.

But I'm unsure about the current state of this project anyways. For me it looks like it has been stalled or even abandoned.
An official answer would be helpful.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
