### ISSUE TITLE
Please include configuration to turn off Epic Roadmap.

### ISSUE THREAD

**Issue by Glenn-Gidlof** [microsoft/featuretimeline#333]
With Epic roadmap in Beta, our enterprise does not release Beta product to production environments.  We use Feature Timeline and with Epic roadmap in Beta.  We cannot release updates to Feature timeline.  If we could hide or disable the Epic Roadmap feature by settings somehow that would help greatly.

**Browser**
Choose a browser
[ X ] IE11
[ ] Chrome
[ X ] FireFox
[ ] Safari
[ X ] Edge

**Version**
[ X ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
