### ISSUE TITLE
Can't open one portfolio plan

### ISSUE THREAD

**Issue by adina0501** [microsoft/featuretimeline#338]
**Describe the bug**
I am having trouble accessing one specific portfolio plan that I need; the name of it is 'b.world.' To clarify, I AM able to access the 'Portfolio plans (beta)' module and other portfolio plans that exist therein. However, when I click on the one named 'b.world,' all I get is a blank screen. (I've attached an image of what my screen looks like after clicking on this particular portfolio plan.)

**Browser**
Choose a browser
[ ] IE11
[X ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
<img width="1128" alt="b world_portfolio plan" src="https://user-images.githubusercontent.com/104380145/165133239-de9a4e50-6c3b-4363-8cc8-1009458bd68e.png">

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
