### ISSUE TITLE
How to customize view in Portfolio Plans (Beta) via priority instead of A-Z sorting

### ISSUE THREAD

**Issue by KimberlyWQ** [microsoft/featuretimeline#339]

**Comment by akuzhan** [comment]
Hi, at the moment when you add epics and stories together, some of the stories goes unrelated epics. Can you please make sure child goes under parent item? 

Best regards,
Abdullah

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
