### ISSUE TITLE
Area Path always shows "Unknown" for Epic Roadmap

### ISSUE THREAD

**Issue by GreenDavidA** [Microsoft/featuretimeline#34]
**Describe the bug**
The Epic Roadmap always shows features under Area Path of "Unknown."

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[X] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/34946195/44281564-3bc4a480-a226-11e8-9d4b-fd6559caa31e.png)

**Comment by Dpetters** [comment]
I see this same issue. Since the features may be from different area paths, does it even make sense to have an Area Path column?

**Comment by navneetg-msft** [comment]
Thanks @GreenDavidA  and @Dpetters , I noticed it yesterday while helping @Dpetters and pushed a fix. Please let me know if this still repros.
