### ISSUE TITLE
Iteration Path is not equal to Start Iteration, neither End Iteration in feature timeline view.

### ISSUE THREAD

**Issue by peepimentel** [microsoft/featuretimeline#340]
**Describe the bug**
Iteration Path is not equal to Start Iteration, neither End Iteration in feature timeline view.

Please find below the picture for the feature timeline view:
![image](https://user-images.githubusercontent.com/104631750/165946312-66b66ed5-e4f0-4a78-b0f7-2f943698dfef.png)

And also the same feature opened:
![image](https://user-images.githubusercontent.com/104631750/165946357-075815dc-375c-47ee-b29e-8a7854d1f91a.png)

Please note that in the feature we can see Iteration Path equal to Sprint 1 and in the feature timeline view the Iteration Start is equal to Sprint 3 and Iteration End is equal to Sprint 4.
![image](https://user-images.githubusercontent.com/104631750/165946475-3c944ff5-e83e-4964-be76-946f6e328df8.png)

I was expecting to see in Iteration Path, either Iteration Start or Iteration End, preferably Iteration End.

Also, it would be great to be able to add the columns Iteration Start and Iteration End in the backlog view that as I far as I'm aware it's not possible nowadays.

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[x] FireFox
[x] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
