### ISSUE TITLE
Epic Roadmap drop down list shows non-epic work items

### ISSUE THREAD

**Issue by AgileCoE** [microsoft/featuretimeline#341]
**Describe the bug**
The Epic Roadmap shows items other than Epic in the drop down list such as Features and Stories.  How can we fix it to only show Epics.  

**Browser**
Choose a browser
[ x] Edge
[ ] Chrome
[ x] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![Epic Roadmap](https://user-images.githubusercontent.com/104907546/166722618-7e98e849-717b-4eb9-9a9b-3d14e4482bae.PNG)

**Comment by danhellem** [comment]
Hello @AgileCoE 

Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
