### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by KittyDreadful** [microsoft/featuretimeline#342]
Hi,

Is this project still being developed/worked on?  

Thanks

**Comment by danhellem** [comment]
Hello @KittyDreadful 

No sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
