### ISSUE TITLE
Timeline does not show features

### ISSUE THREAD

**Issue by KevinSzr** [microsoft/featuretimeline#346]
Hi,
I have my project set up with a Basic process. My team backlog contains epics, issues and tasks. All of them are assigned to an iteration.

In the "Feature Timeline" I see a timeline of my epics without issues. 
The "Epic Roadmap" would not open (Epic Roadmap requres at least two levels of Portfolio Backlogs.)

Is there anything I may have done wrong?

Best reagrds,
Christian

**Comment by danhellem** [comment]
Hello @KevinSzr 

Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
