### ISSUE TITLE
Unable to remove work item from Feature Timeline

### ISSUE THREAD

**Issue by abhaymsft** [microsoft/featuretimeline#347]
**Describe the bug**
Once a feature has been dragged onto the feature timeline, there isn't a way to delete it. This causes a problem because even though it is no longer in our dev schedule, it still looks like it is and causes confusion.

Please let me know if there's a way to get it off the timeline! Thank you :)

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/110636193/184735535-c201c262-4f9c-4ccd-8359-efc4176a411c.png)

**Comment by abhaymsft** [comment]
bump - is there anything we can do to give this priority? i'd be happy to pay a bonus to expedite this

**Comment by danhellem** [comment]
@abhaymsft Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
