### ISSUE TITLE
Feature timeline is displaying wrong iteration as current iteration

### ISSUE THREAD

**Issue by LukasK07** [Microsoft/featuretimeline#35]
**Describe the bug**
Feature Timeline is displaying wrong current iteration. We do have a valid current iteration set for our project teams.

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] VSTS
[ ] TFS 2017 Update 2/3
[x] TFS 2018

**Screenshots**

![wrongcurrentiteration](https://user-images.githubusercontent.com/38733517/44331408-ecb28580-a458-11e8-819b-03a586e1eafe.PNG)

**Comment by LukasK07** [comment]
short notice: today current iteration is set to the correct iteration, we havent changed our configuration

**Comment by navneetg-msft** [comment]
Could be a bug related to timezone, I see a pull request related to this and merged it yesterday.
Please reopen this issue if you observe it again.
Please provide additional details e.g. your timezone.

**Comment by LukasK07** [comment]
Hi,
Bug appears again today, 
- Timezone of Server ist UTC+1 (Region: United States)
- Timezone of Clients:  UTC+1 (Region: Germany)

I'll try to install ms-devlabs.workitem-feature-timeline-extension-0.0.327 and will give u a feedback.

Thanks
