### ISSUE TITLE
"_b is undefined" error when opening portfolio plan

### ISSUE THREAD

**Issue by kristamyers** [microsoft/featuretimeline#350]
**Describe the bug**
When I try to open one of my portfolio plans, I get an error that says "_b is undefined," and the plan is not displayed.  This plan was created several months ago and had been working until a few days ago.  Other portfolio plans open correctly.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[X] FireFox
[ ] Safari

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/112491593/187452999-717361d9-f224-4876-8d65-873ffa1d8557.png)

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
