### ISSUE TITLE
Progress tracker count not working!

### ISSUE THREAD

**Issue by dthapa-optum** [microsoft/featuretimeline#353]
Great extension but the progress tracker is not working for me. For instance says 0/3 even though all user stories within the feature are complete. Any suggestions

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
