### ISSUE TITLE
Portfolio plan | nothing appears 

### ISSUE THREAD

**Issue by Hiooo** [microsoft/featuretimeline#354]
**Describe the bug**
Portfolio plan shows empty when trying to open it. This plan has been working on for some time, but suddenly nothing appears. 

**Browser**
Choose a browser
[ ] IE11
[ x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![portfolioError](https://user-images.githubusercontent.com/15194429/193251489-834321f6-c8b4-4cf3-913d-2a5bb6d6936f.JPG)

**Comment by AminTi** [comment]
Thanks for reporting

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
