### ISSUE TITLE
Feature Timeline link disappears

### ISSUE THREAD

**Issue by nadaavthivy** [Microsoft/featuretimeline#36]
**Describe the bug**
The Feature Timeline link on the Backlog Items page disappears. Initially we were having the same problem in #18 (i.e. the scripts were running under http while TFS was running under https).

As per #18 , yesterday we uninstalled and re-installed the extension. This didn't help initially, but when we restarted the TFS server, the links appeared again, and the scripts were now properly running as https. 

Today, the links disappeared again. Restarting the TFS Server brought them back.

Any assistance in troubleshooting this would be much appreciated.

**Browser**
Choose a browser
[ ] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] VSTS
[ ] TFS 2017 Update 2/3
[x] TFS 2018

**Screenshots**

**Comment by navneetg-msft** [comment]
Thanks for reporting the issue. Unfortunately this seems related to server/network configuration which is outside of my expertise. Please check the server's event log to see if there are any Errors in Team Foundation Server Debug logs, you may also open a support case with Microsoft.
Please reopen the issue if you need further help.
