### ISSUE TITLE
Portfolio Plan: not able to find feature

### ISSUE THREAD

**Issue by Grieser** [microsoft/featuretimeline#361]
**Describe the bug**
Our organization uses one project across all of our teams so we have quite a few features and epics.  When attempting to add items by feature, the list shows features 1 - 539206 (non inclusive).  I'm trying to locate features in the 800,000 range and they don't show, even when filtering.  I would like the drop down to show all features in a project, or add additional functionality to narrow down the list it's pulling from.   Without it, I won't be able to use the portfolio at all as new features continue to be added.  Thanks!

**Browser**
Choose a browser
[X] Edge
[ ] Chrome
[ ] FireFox
[ ] Safari
[X] Brave

**Version**
[X] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/5523661/198399161-e1e108fe-376e-4813-84bb-3fd65622a4e5.png)
![tempsnip2](https://user-images.githubusercontent.com/5523661/198399169-ebe596ec-bc57-46fa-85b1-ad10ec152b51.png)

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.

**Comment by danhellem** [comment]
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.
