### ISSUE TITLE
Extension is giving me no In-progress feature message, and the top part of UI is missing

### ISSUE THREAD

**Issue by Rickm1970** [Microsoft/featuretimeline#38]
My IT department installed this extension for me but it is not working properly. Most of the UI is missing and the timeline states that there are no in-progress features. Is there anything I need to download locally to get this extension to work? I love the idea of this extension and would really like to use it.

**Comment by Rickm1970** [comment]
Here is an error from the Chrome console. 

Content?bundle=vss-bundle-basejs-vLDQ_BPnMflh1yV4rhP43SsHlun31XvwYB1svh7haP9E=:5 GET http://msp-tfs-02:8080/tfs/ISS%20SAFe%20Engineering/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/workitem-feature-timeline-extension/Data/Scopes/User/Me/Collections/%24settings/Documents/ef9a80e5-b881-4ffb-a109-541a9c8cc4f6_iterationDisplayOptions 404 (Not Found)
send @ Content?bundle=vss-bundle-basejs-vLDQ_BPnMflh1yV4rhP43SsHlun31XvwYB1svh7haP9E=:5
ajax @ Content?bundle=vss-bundle-basejs-vLDQ_BPnMflh1yV4rhP43SsHlun31XvwYB1svh7haP9E=:5
(anonymous) @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:52
c @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:28
(anonymous) @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:28
u.promiseDispatch @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:28
(anonymous) @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:28
t @ Content?bundle=vss-bundle-common-vbimGxpdk-xftd6QLkOgbNC56tgITZQ6eLLBKeNd7lRM=:28

**Comment by navneetg-msft** [comment]
Sorry to hear that you are getting this Error, I have just published an update, can you try again?

**Comment by navneetg-msft** [comment]
Closing due to no response.
