### ISSUE TITLE
Select the portfolio backlog for the timeline

### ISSUE THREAD

**Issue by Stefan2222** [Microsoft/featuretimeline#44]
We are using 2 portfolio backlogs above Epic: Goal and Vision. It would be great to choose the portfolio backlog that is used for the timeline and the roadmap. So we can see our Goals on the timeline and our Visions on the roadmap. It would be even better to have separated timelines for each portfolio backlog.

**Comment by navneetg-msft** [comment]
This is a good suggestion. It is a bit expensive to implement, I will watch for upvotes to see how many other users need this and decide based on it.

**Comment by Stefan2222** [comment]
Without this feature, the feature timeline is useless.

**Comment by navneet-g** [comment]
Thanks @Stefan2222  for the feedback. Unfortunately I do not have time to implement this feature. If you can find someone who can help implement. I can help them by ramping up in design and implementation.
