### ISSUE TITLE
How do I access it from the UI?

### ISSUE THREAD

**Issue by yvanpinto** [Microsoft/featuretimeline#45]
We have installed the extension in our TFS instance.

How do I access it from the UI?

**Comment by DavidDeSloovere** [comment]
![image](https://user-images.githubusercontent.com/352626/45623172-b6334f00-ba86-11e8-81d0-ef05f9f51be0.png)

**Comment by navneetg-msft** [comment]
Thanks @DavidDeSloovere  for responding to the issue.
@yvanpinto  please let us know if you have any feedback.
