### ISSUE TITLE
Completed US progress bar/count always zero

### ISSUE THREAD

**Issue by rschiefer** [Microsoft/featuretimeline#46]
**Describe the bug**
This used to work but not sure when it stopped.  The two features in the screenshot below are both about 80% complete.  All features on the board list 0 stories completed.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[X] Edge
[ ] Safari

**Version**
[X] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/1071761/45954378-7dd5c880-bfd2-11e8-80c9-aaf81937ede7.png)

**Comment by navneetg-msft** [comment]
Can you send the screenshot of the settings section at the top of the feature timeline as well?

**Comment by rschiefer** [comment]
This what you need?

![image](https://user-images.githubusercontent.com/1071761/46182413-52343600-c291-11e8-90e2-1d1b4e8b288e.png)
