### ISSUE TITLE
Can I make Epic Roadmap (Beta) to show feature in another Project in Azure DevOps

### ISSUE THREAD

**Issue by wpat** [Microsoft/featuretimeline#50]
Hi I am relatively new to DevOps. My team manages the EPICs and we "move" certain development features to the dev team's project when the dev team is ready to work on them. Those features are on the other board, but are children of the EPIC on my board. 

I want to show an EPIC roadmap for all the features under a particular EPIC that I manage, but if a feature has been moved to the other project, it will not show up. The warning message says: 

"Please add following iterations in team settings to include theses workitems". Basically it is telling me to add the other team's iteration to my board. 
![2018-10-09_14-45-59](https://user-images.githubusercontent.com/44004193/46692505-7703a400-cbd5-11e8-83fc-04bfc129141c.png)

I was able to see features from different projects in the "Plan" by customizing the plan settings, but it is not clear to me how to control this "feature in different project" issue in EPIC Roadmap as well as Feature Timelines.

It is similar to the query across projects functionality. It would be very helpful if we can access the query behind the roadmap.

Thanks!

Winston

**Comment by navneetg-msft** [comment]
Thanks for the feedback @wpat , currently this is not supported, and it is not easy to support considering each project has different area and iteration paths.
