### ISSUE TITLE
Features assigned to an iteration should appear even without child stories

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/featuretimeline#51]
I can understand not wanting to show the entire feature backlog. I would argue that something assigned to an iteration meets the threshold for visibility in the feature timeline.

**Comment by navneetg-msft** [comment]
Thanks for the feedback @jdshkolnik and @wpat , we show the features if they are in Active status even when they do not have child stories. Can you check if the Feature is marked as active? If not you can still pull it from Plan Feature pane and drop it on the timeline.

**Comment by jdshkolnik** [comment]
Define “active”.

**Comment by navneet-g** [comment]
The Features that are in Active or In Progress State.

**Comment by navneet-g** [comment]
Closing as I assume my response above answered the question, please open a new issue if you have futher questions.
