### ISSUE TITLE
Feature iteration path vs end iteration

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/featuretimeline#52]
I would expect the timeline end iteration for a feature to automatically become the feature's iteration path if the path is later. I'd expect similar behavior if path is changed to earlier. This can then be overridden -- as it works now -- but would then reset if the iteration path is modified again.

**Comment by navneetg-msft** [comment]
Thanks @jdshkolnik for the feedback. Feature timeline stores the start/end iteration in extension storage. There is no good way of syncing the iteration between two without loosing users explicit overridden value.

If you click on "info" icon it shows what values are used to calculate start/end iteration in Featuretimeline and you can manually clear it.

**Comment by navneet-g** [comment]
Closing as I assume my answer was sufficient, if not please reopen.
