### ISSUE TITLE
Feature Request: Update Timeline/Roadmap after editing feature

### ISSUE THREAD

**Issue by florian-d** [Microsoft/featuretimeline#53]
Example: When you change the feature status, the timeline does not get updated automatically. You have to reload the page. 

It would be great, if the timeline gets updated automatically.

**Comment by navneetg-msft** [comment]
@florian-d  thanks for the feedback, currently the extensions do not get notifications for all changes to work item, so I can not implement it without force reloading the entire timeline when work item dialog closes. In past we used to do that and users didn't like it as we used to refresh even when no significant changes were made.

Un-Fortunately I cannot fix it easily without regressing other scenarios :(
