### ISSUE TITLE
Toggle Beta Features On/Off

### ISSUE THREAD

**Issue by drewan50** [Microsoft/featuretimeline#54]
We need the ability to toggle on/off 'Beta' functionality.  For example the epic timelines have 'Beta' all over it, and it would be ideal to give users the options to turn this functionality off.

**Comment by bsc7080hum** [comment]
I definitely would like to see this as a configurable option to display new beta functionality on/off.

**Comment by navneetg-msft** [comment]
Thanks @drewan50  and @bsc7080hum for the question, I am soon going to make Epic Roadmap non-Beta. I don't have any Beta features plans for now, once I have will provide a way to toggle them on/off.
