### ISSUE TITLE
Question: Where does the end date for a Feature get saved?

### ISSUE THREAD

**Issue by luiscabanillas** [Microsoft/featuretimeline#56]
**Question**
In the plugin, you are able to extend the duration of a Feature for more than one iteration. I would like to know where that end date is saved and if I can use that for querying/reporting in AzureDevOps (VSTS).

**Version**
[X] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by navneetg-msft** [comment]
@luiscabanillas this end date is stored in extension storage which is not available for querying.
