### ISSUE TITLE
Feature timeline showing as a list not plan view

### ISSUE THREAD

**Issue by KChandG** [Microsoft/featuretimeline#60]
**Describe the bug**
Feature timeline showing as a list not plan view

**Browser**
Chrome

**Version**
 Azure DevOps/VSTS

**Screenshots**
![feature roadmap](https://user-images.githubusercontent.com/11536423/49023714-b8551080-f18f-11e8-9e08-12a2ebff51ad.png)

**Comment by navneet-g** [comment]
Strange ... I see there are 6 upvotes many users are experiencing it ... I am not able to repro, do one of you have time for a live debugging session?

**Comment by navneet-g** [comment]
Closing the issue, please reopen when you have time for live debugging.
