### ISSUE TITLE
Displayed iterations

### ISSUE THREAD

**Issue by tkollo** [Microsoft/featuretimeline#61]
I can only see features until end of year no matter what I set for 'View Sprints', what determines the iterations that can be displayed?

**Comment by navneet-g** [comment]
The team needs to subscribe to team iteraration. Check following for more information.

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-team-defaults?view=vsts&tabs=new-nav#select-team-sprints-and-default-iteration-path

**Comment by navneet-g** [comment]
Closing as I did not hear back and assume it answered the question.
