### ISSUE TITLE
Cannot tell what criteria is populating the Feature Timeline

### ISSUE THREAD

**Issue by Flightless-Dutchman** [Microsoft/featuretimeline#70]
On my Portfolio backlog on VSTS the Feature Timeline is showing some of the Epics and not others. When I compare, the Features in those epics are in the same states / iteration paths etc... What exactly is driving the population of the Feature Timeline?

If I can get the epic to appear then I can manually insert the Features using the 'Planning' checkbox.

**Comment by navneet-g** [comment]
I assume this question is about Feature Timeline tab, we show Inprogress Features assigned to current team's Area and Iteration path.
Please let me know if this answers your question.
