### ISSUE TITLE
Plug-in marked as only supporting Azure Devops

### ISSUE THREAD

**Issue by nschonni** [microsoft/featuretimeline#72]
**Describe the bug**
Currently the metadata of the extension manifest is only targetting the Azure DevOps
https://github.com/Microsoft/featuretimeline/blob/c8d0d038657f670448e3fdf3c07e73ed4f7034a0/vss-extension.json#L9

The `.Cloud` should be removed from the end to indicated that both on-prem and hosted are supported

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[x] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by navneet-g** [comment]
Thanks @nschonni  can you send a PR?
