### ISSUE TITLE
Missing html contentType

### ISSUE THREAD

**Issue by pabrams** [microsoft/featuretimeline#73]
**Describe the bug**
In IE, when published to TFS 2017U3.1, html pages won't load.
In Chrome, when published to TFS 2017U3.1, html pages are downloaded instead of displayed.

Note that you will be unable to reproduce, because your extension doesn't work in TFS at all (need to remove `.cloud` from the target).

**Browser**
Choose a browser
[X] IE11
[X] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

The cause is missing contentType properties on the html files attributes in vss-extension.json.  This is almost always a problem in extensions that were published to the marketplace, so I guess that publish process must somehow be adding those content types.  Can you explain?

Note that you will be unable to reproduce the problem, because your extension doesn't work in TFS at all (need to remove `.cloud` from the target).

**Comment by navneet-g** [comment]
Thanks @pabrams  can you send a PR? I have several users using the extension on prem and I also just tried it and it works.
