### ISSUE TITLE
Lock the iterations at the top (Fixed)

### ISSUE THREAD

**Issue by drmigli** [Microsoft/featuretimeline#74]
Is there a setting that allows you to keep the Sprint headers static, equivalent to frozen in excel?

**Comment by drmigli** [comment]
![request_timelinefeature](https://user-images.githubusercontent.com/23175982/50100721-4315b200-0208-11e9-8617-6d7ea19766c1.JPG)

**Comment by drmigli** [comment]
This yellow box fixed

**Comment by navneet-g** [comment]
Thanks @drmigli , this is currently not implemented and require some major refactoring, I can think about it in next major release. For now I am closing the issue.
