### ISSUE TITLE
Future iterations are not showing

### ISSUE THREAD

**Issue by royaln** [Microsoft/featuretimeline#76]
**Describe the bug**
The Feature Timeline only display iterations up to the current iteration. The current iteration is _Dec 31 - Jan 20, 2019_. The following iteration _Jan 21 - Feb 03, 2019_ assigned to the team with active (In Progress) work items does not display in the timeline. 

**Browser**
Choose a browser
[ ] IE11
[x ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
### Iterations assigned to the team
![image](https://user-images.githubusercontent.com/898167/50841720-531a4080-1333-11e9-893b-155629088fad.png)

### Feature Timeline
![image](https://user-images.githubusercontent.com/898167/50841827-88269300-1333-11e9-96c7-6a0bdbeb7e5c.png)

**Comment by navneet-g** [comment]
This is strange ... will you have time for live debugging?

**Comment by navneet-g** [comment]
Closing due to no response.
