### ISSUE TITLE
Suggestion: Visualization of features should not depend on adding user stories to sprints

### ISSUE THREAD

**Issue by jlundstocholm** [Microsoft/featuretimeline#82]
Adding user stories to sprints and then to features give a really nice overview of feature progress.

![image](https://user-images.githubusercontent.com/683942/52170008-0400d900-2742-11e9-9092-d29a8f71f4cc.png)

However - it really goes against the agile principle of "just-in-time planning". We would never add user stories to sprints so far in the future as the "Feature timeline" requires.

What we would do when doing "Feature planning" is this:
We would line up the features and distribute them over time - as per our best knowledge/guess of what the teams will be able to accomplish. We would use the built-in fields on portfolio work items (Features - and Epics) "Start date" and "Target date".

Of course we would add user stories to the features, but we would never add them to sprints until we can "see" the sprint in the near future.

My suggestion is this:

Create the visualization (possibly by opting in on this in the configuration) of the Feature timeline by the "Start date" and "Target date". We love the roll-up of user stories on the Features and the "Progress indication", so please keep this functionality.

**Comment by nicmart84** [comment]
> 
> 
> This is already possible in Feature timeline. Please click on the info icon on top-right corner of the Feature and override start and end iteration for the feature in the dialog.

This only allows to select sprints. Seems there is no current way to plan a roadmap that is not sprint-based.

**Comment by navneet-g** [comment]
Yes that is correct, the product uses Iterations for planning and thus Feature timeline also uses iterations for planning.

**Comment by nicmart84** [comment]
I believe this should be reopened as this is a critical ability for feature planning for teams who use Agile and don't plan sprints until closer to the date. It should be possible to plan work independent of sprints.

**Comment by navneet-g** [comment]
Thanks @nicmart84 for the feedback. I closed it as I will not have bandwidth to create two separate options to support both Sprint based and Calendar based visualizations. If you can find some resources to implement this feature, I can help in sharing the design and have them ramp-up.

**Comment by mpseidel** [comment]
@nicmart84 if you're interested please hit me up on Twitter (@thomsen_digital)

We have a product roadmap extension in the works and would love to collaborate with you.
