### ISSUE TITLE
Epic Roadmap: logic behind inclusion in road map is hard to figure out

### ISSUE THREAD

**Issue by jlundstocholm** [Microsoft/featuretimeline#83]
We have our teams set up such that they are given an area path (e.g. <project name>\<Team name> . Below this are sprints, e.g.

```
project name
  team name
    sprint 01
    sprint 02
    ...
```

When we create epics for a team, these are placed in "project name\team name" iteration path. The same goes for Features. Adding them to a sprint does not make sense (to us), since work items on portfolio level can be cross-sprints. User stories are added to sprints, ofc, but that is besides my point.

However, it seems to me that the requirement for having Epics and Features show up in "Epic Roadmap" is that all of them are added to a specific sprint.

If I remove a Feature from a sprint (and put it back in the Feature "root" backlog) it disappears with this message:

![image](https://user-images.githubusercontent.com/683942/52181178-7e3b6700-27ef-11e9-9351-d801d7f15287.png)

This logic is a bit off to me. Since the items visualized in the Roadmap are Features, Epics and Features should not have to be added to specific sprints to display them. Visualization should depend on the user stories added as children to them (just as for Feature timeline).

**Comment by navneet-g** [comment]
Closing the issue as no followup questions were asked. Please open a new issue or reactivate this if you have further questions.
