### ISSUE TITLE
Epic Roadmap

### ISSUE THREAD

**Issue by fthkucuk** [Microsoft/featuretimeline#84]
**Describe the bug**
I see all work items type in Epic Roadmap. I just see epic work items before

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps Server 2019 RC1
[ ] Azure DevOps Server 2019 RC2

**Screenshots**

![epic roadmap](https://user-images.githubusercontent.com/46280608/52270152-2157c200-2951-11e9-80cd-95e238743038.PNG)

![backlog](https://user-images.githubusercontent.com/46280608/52270141-1735c380-2951-11e9-80a4-8046d88cc122.PNG)
I attached 2 screenshot. One of them epic backlog another one epic roadmap.

**Comment by navneet-g** [comment]
Please share backlog configuration for the project.
https://dev.azure.com/<accountname>/<projectname>/_apis/work/backlogconfiguration

**Comment by navneet-g** [comment]
Closing due to no response.
