### ISSUE TITLE
Epic Roadmap Suggestion: Start Iteration of Successor should not always immediately follow Predecessor

### ISSUE THREAD

**Issue by jeriklindgren** [Microsoft/featuretimeline#86]
If a Successor is scheduled several sprints after the completion of its Predecessor, the Successor currently gets shown in the Epic Roadmap as starting in the iteration immediately following the Predecessor.  I would expect empty iterations between the two, since a Predecessor completing does not necessarily mean that a Successor will start.  It should be up to the team to schedule the Successor at *any point after* the Predecessor, not necessarily in the sprint immediately following the Predecessor.  A Successor cannot complete prior to the Predecessor, but it should be able to start at any point in the future after the completion of the Predecessor.  Just a suggestion to improve an already very useful tool.

**Comment by navneet-g** [comment]
Is the iteration path to the successor set to Backlog iteration? If yes then this is the best guess the tool can do. Please set the iteration path to a future iteration and let me know if Epic roadmap does not honor it.

**Comment by navneet-g** [comment]
Closing due to no response.
