### ISSUE TITLE
Feature Request: Ability to see Impediments/Risks on the Feature Timeline

### ISSUE THREAD

**Issue by adesai0** [microsoft/featuretimeline#87]
I wanted to know it there is a way we could view any risks/impediments either on the Feature or when we pull up the PBI view with iterations?

**Comment by navneet-g** [comment]
Currently there is no way to show that information. Where do you store such information?

**Comment by adesai0** [comment]
Ah..I didn’t get what you meant by “Where do you store such information?” Impediments and Risks are usually added at the PBI or the Feature level.

Thanks,
Aatmaja

________________________________
Aatmaja Desai

Inovalon, Inc.

(301) 809-4000 x1903

4321 Collington Rd

adesai@inovalon.com<mailto:adesai@inovalon.com>

Bowie, MD 20716

**Comment by navneet-g** [comment]
Please share  a screenshot where you see Risks and Impediments.

**Comment by adesai0** [comment]
What I was trying to ask was:

For example, I have an impediment open under a PBI (Screenshot 1), can that be viewed on the Feature Timeline (Screenshot 2)?
1.
[cid:image001.jpg@01D4CDAC.70E1EB30]
2.
[cid:image002.jpg@01D4CDAC.70E1EB30]

Thanks,
Aatmaja
________________________________
Aatmaja Desai

Inovalon, Inc.

(301) 809-4000 x1903

4321 Collington Rd

adesai@inovalon.com<mailto:adesai@inovalon.com>

Bowie, MD 20716

**Comment by navneet-g** [comment]
I don't see the screenshots, please re-attach.
