### ISSUE TITLE
Nested bars vs 1 bar per row

### ISSUE THREAD

**Issue by Vanbebar** [Microsoft/featuretimeline#88]
We would find this extension much more useful if each bar did NOT require its own row. It would be much more user friendly (especially when showing a lot of "closed" Features) if the bars could nest within the same row - when appropriate.

Example: 3 features start & end in succession (2 sprints each) -- Have these bars horizontally together within the same row - rather than each feature bar taking up its own row. This makes the view more compact and avoids a road-map getting way to vertical in nature - which makes it much harder to absorb and understand.

**Comment by navneet-g** [comment]
Thanks @Vanbebar this is great suggestion. I will consider it for next major release. These days I am bit busy at work so I can not promise when that will be.
