### ISSUE TITLE
Add ability to "pin" left-most (Epic?) column

### ISSUE THREAD

**Issue by craigeddy** [Microsoft/featuretimeline#9]
As I scroll to the right (forward in time), I would like to see the left-most column pinned. This will allow me to see the Epic associated with the Feature items in the timeline.

**Comment by navneet-g** [comment]
This is a known feature request, it requires a large refactoring. To help that we have introduced Three and Five sprints view. You can navigate to next and previous sprint, I know this is not ideal.
If you have time and can contribute, please send a Pull Request and we can take it from there.
