### ISSUE TITLE
Feature Timeline: Features not visible when in custom state

### ISSUE THREAD

**Issue by andreasthulin** [microsoft/featuretimeline#90]
**Describe the bug**
For the Process we're using in our project, we have created a couple custom States for Features, e.g. "Ready to Release". When a Feature is moved on the Kanban to the Ready to Release column (and hence State), it disappears from the Feature Timeline.

**Browser**
Choose a browser
[ x] IE11
[ x] Chrome
[ not tested] FireFox
[ not tested] Safari

**Version**
[ x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/11869098/53102137-6243ff00-352b-11e9-8519-3ec079497ec1.png)

**Comment by andreasthulin** [comment]
Did some more testing and realised this may be a bit more complex than anticipated. The State "Resolved" also makes the Feature disappear from the Feature Timeline. However, when I move "Ready to Release" from State Group Resolved to State Group In Progress, it appear fine on the Feature Timeline. Tricky.

**Comment by navneet-g** [comment]
This is strange can you share output of the backlog configruation for the project.
https://dev.azure.com/<account>/<projectname>/_apis/work/backlogconfiguration

**Comment by navneet-g** [comment]
Closing due to no response.

**Comment by daliso** [comment]
I am also facing the same issue when a feature is moved to the 'Resolved' state group

**Comment by daliso** [comment]
@navneet-g , would you be able to reopen this bug?
