### ISSUE TITLE
Feature timeline not loading - Firefox 65

### ISSUE THREAD

**Issue by davidtprice** [Microsoft/featuretimeline#91]
Feature Timeline will not load in Firefox 65.0.1. The Epic Roadmap loads fine with the same browser. Problem is not seen with Chrome.

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[x ] FireFox 65.0.1
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[x ] TFS 2018

**Screenshots**

**Comment by navneet-g** [comment]
Please try with the latest version, I published an update yesterday. Also please provide error message in Browser console if any to debug it further.

**Comment by davidtprice** [comment]
It is working. Thank you for fixing.

On Mar 20, 2019, at 1:53 PM, Navneet Gupta <notifications@github.com> wrote:

Please try with the latest version, I published an update yesterday. Also please provide error message in Browser console if any to debug it further.

**Comment by navneet-g** [comment]
Awesome ... :)
