### ISSUE TITLE
Export feature timeline for a report

### ISSUE THREAD

**Issue by natke** [microsoft/featuretimeline#94]
**Describe the bug**
I am trying to export the feature timeline into a report. I have tried using Browser -> Print but the timeline is truncated to one page. Is there any other way of exporting the feature timeline?

**Browser**
Choose a browser
[ ] Chrome
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS

**Screenshots**

**Comment by navneet-g** [comment]
Unfortunately not.

**Comment by billpmay** [comment]
Love this extension! Thank you for creating this. I would vote for adding an export / print feature.

**Comment by jthomerson** [comment]
Same here. We use this for reporting plans at a quarterly level - which features will make it somewhere into the quarter, but we need to be able to report on that. To be able to print the Feature Timeline tab would be great.

Also - maybe as part of this, or maybe it's a separate request - we need to be able to include the "end iteration" as a column in queries.

**Comment by miniseb** [comment]
hello, 
as a workaround, can we at least get the start iteration and end iteration by query? If so we can query in excel and rearrange it the way we want.

**Comment by jthomerson** [comment]
@danhellem can you point us to details on what was completed?

**Comment by danhellem** [comment]
Actually, nothing was completed on this. We are closing old issues as this project is not being maintained further.
