### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by sasibuddy** [Microsoft/featuretimeline#96]
Login page is not working while i am provide valid username and password

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by navneet-g** [comment]
@sasibuddy Feature timeline do not have its own Login page. Are you able to visit other pages?

**Comment by navneet-g** [comment]
Closing due to non reply ... please reopen when you have furhter information @sasibuddy
