### ISSUE TITLE
Feature Request: Add Information on the features by Settings

### ISSUE THREAD

**Issue by Christ0phH** [Microsoft/featuretimeline#99]
Similar to the settings for delivery plans...

![2019-03-19_16h00_50](https://user-images.githubusercontent.com/42636398/54622806-89c6b280-4a6a-11e9-864d-1ce0f0fbb2e2.png)

...it would be great to add additional information to the ...
![image](https://user-images.githubusercontent.com/42636398/54616878-a827b080-4a60-11e9-9dbb-6661b1126e5b.png)  view.

When activating the details it could look like this:

![2019-03-19_16h17_02](https://user-images.githubusercontent.com/42636398/54622814-92b78400-4a6a-11e9-84c9-84cb94143372.png)

**Comment by navneet-g** [comment]
Thanks for the feedback @Christ0phH , I will consider this in next major release, but I don't have timeline to commit to it yet.
